test_inp = [
    'accuuutaaaiiiqqqpppzmhhqqqyqzzzoeddkkbbbmmmcccc 2',
    'kqqquuccszzjtttiieggghepp 4',
    'ppgrzjiitttttbbvvvviiipptnnngghhhnnnbbb 3',
    'bbbmmiiooxxxsszrlpppftttiiibaaafffkkknnqqqwffkk 5',
    'raazzzssslllscxcmmcdlllqbqqohhbtuuukkkkk 3',
    'ejjjccuoootttczvvvvvvggglnttucciiihhnnnjbqqqjfffl 1',
    'aauzzzfiiiwjaaammmzzufu 4',
    'lgxxxqqquuaanngyjjjzzbgmmmiii 2',
    'hhtmzzzsssoooiieemvvzzzddiiiff 2',
    'llkklllsssehhvvvvwcssgyyyiiihcwwnnnvvvkkvssiiiccc 2',
    'xxxkfffddlllynnnpppteuuuiiyyssfffppffgggvvzzzzrzzzzyy 1',
    'ppexxqqqeetmmmlllggffmmnnnuuuggaaammmmmwwoaq 3',
    'gggfffbbooomfffnoldmllmddeetttwwbbnhhvv 5',
    'cccsssbbbggmmkkbbvvssaaattuubbbeeewwqqlllgggkwww 1',
    'lllommmfffeeenbbbkkcjjjuuccceeeqqqccc 2',
    'qqqhhhddmmtttmdillltqqqo 2',
    'ffffffddoolnpjpvvvpaaaaammuuu 1',
    'evvxxxxxxsssqqqvddveyynnncllldccoorrxxxtaazupppb 5',
    'xxxyeejjkkkyyaammmjdddppjjjnnnccrdddsgggvvdddr 4',
    'muurkkbbddxxmjbbxiiivvvpppttfffhhxxgggvvvllytookk 3',
    'cuuummtthhhzzzuuurhhzzzcccccnnbkkmcccxxdddooc 2',
    'iiivvvvuuuiimsmmmbccmddrrll 4',
    'qcccduuuucaahhuugggwwttrriiittjjjwssssool 3',
    'fttrrrsssnnabbbpppvvwwwiimrrroooqqpppiilllbbbrrr 2',
    'rrbbnnnrnertttowwatttbbbfffxddllttm 2',
    'mmmoymmhhjjjmmeccczyyyqqqqqqbbfhhzjjjchhvvvonnt 4',
    'lllhkkkkeqqqtttxsssoooeesssssyyydddooojjjnnzppkkf 2',
    'owwxxxeeeoooyyyxnnnhoorttmbbbwwwpppbbayyf 3',
    'pprrreewiivvkkgy 4',
    'lpjttbbhheeennjjgggoooqgggbbbjjoooqqq 1',
    'vvvsszzyyykkkwaayyyzlssppzzzkppptvvjjjoollla 2',
    'llllwoqdjjxxbgguulcctttgvrrrjwwuqppydddh 4',
    'ppddrrwwyyyuunnnxbllaakkkpphhhhhccfcccmmmvbbbqqquo 5',
    'pppjbbbbiirrrhhhopaqquubbbyyyukjjxxttt 3',
    'bbbvjjgqiibbsuuuttovoqgguuuiiiuuppkjjqqq 3',
    'llloootttzzzsooxxqrrrooozzzfffooobbmmmquuullmxllhcccm 3',
    'pffaannuugggljguf 3',
    'rmhhhrrttbbbblllkkkmm 5',
    'yyxxxttunooolirrrvvmuuhhhnnnllldddddxxxtttfffxxcclll 5',
    'mqqkkmqqqdrrhhhnl 3',
    'ttjjggeqiibbbsssuuughzrruummmzzaauuujggpppzzogmmm 4',
    'jjjtkyyyyyyffhhhffnnqtuuup 2',
    'kaaahhkcbkktooovvvnee 1',
    'ggeeewwbbbmmzkkqqrrfjjj 2',
    'wwyllpppfffffllttzlllrrrzzzeeeqqyuuuxggggg 5',
    'uuufyyudddittttttzzzlllyneeeppttjyoorrrrrsssss 3',
    'wwffkkkeennnddssccwrrdddduuue 4',
    'yyeesyuuuevvvqqpwwwddcccblllbbb 5',
    'lllueeemaeegrrrwwiiiqqxxgggbbbbbiooooiivvyy 3',
    'smmmeuzeexxxxaaxxgbb 4',
    'wwwhhhwzsssfffjzgggvvwddrrssseeecc 4',
    'xxmmmnrrtddppplllexxyrjdddsppxx 1',
    'mskkkgggqzzryyllliiitttofffe 1',
    'olaabbpvvdnnndjjjynnsssxxbbcccmmssseeehroojjxxe 3',
    'lqwbbbqqqggddfffpppiiivvvhhjjzxxaaxxmmffinhrkkk 4',
    'bbyooqqqpppccchhhfffqq 1',
    'zzjjyyppxxxtttxcccmmmvtttqqeekpppaannxffrrouuugggeee 2',
    'mmbcqqqcccnnnrrrwwwcciwvvxxxf 2',
    'mppaaiiiccivaaammrknnncubbpnnlllzzzxxccimmmh 5',
    'qwuiiizzqqyhhfxxx 2',
    'wrrueeddnnfffxennnoomm 4',
    'yjjjzzznnddrrqddvuhyyyddggpppiiffmmmpttizzsss 5',
    'gggpppjjjywwwxxxnnndddnnjjjktttzzzwwyyxxxhhhoofffbb 3',
    'oookkktttkksshnuuupppggguuuaajggllqqqeeeokksfffaaabbballl 4',
    'gllrpppuukwwggmstffnnhhnie 4',
    'uuuszgoooojaaafffrrlssxxxkkkabnnccc 2',
    'xxmbswwooofflxxvooiggghhzzz 4',
    'wwpppooosssssndddweeebddbbbgrqqqnnmrvvvvdddhhhq 2',
    'sssiiyysskkqqqyykkuziibbjjjm 5',
    'uuucccpctfrrqqqccckhwiiinnnyllggta 4',
    'hhhnndoiiinnaaacuuxxxgggrsssnllyykkhvvvxmmmyyyimmmb 5',
    'iivnssqqlnvvddr 5',
    'ccjjjpppyyhhhhffllllllxxxaiiioaaagghhhyyynnmqqccc 5',
    'jjjbuxxxxjjnnnjjjeeexxjjjppqdddmmmxxxxypqqqqttss 2',
    'mgggrrcccvvwwggyyyggdupss 4',
    'gggvvvcccvvvlrrrzzziiilxxxlllaaaeemmmrrreeeuueeeuauuucii 2',
    'pzzkkvvvjyyjjggguuummmzzooogobnxxkkkzzbb 4',
    'nnooonnnjjjiiipppjmvvvwwjj 3',
    'jjjnnnooqoypphhgxcjbb 3',
    'kdneeeuvvvrffiilllnjjjxwwaaafffjjt 4',
    'ffwwwtttssjjjnnoooowwwggbbbhhlb 3',
    'nnnuyycccqqtttudiiissslllppwwttt 3',
    'teeeeeyyyccrttddtt 1',
    'iigggaggnniiacuzzzzz 2',
    'mmssmmooouuuaawpcccgggwwwccxxxtttkkggllzzipppavvv 1',
    'onhhhxwwggkkhobbdddzzxxx 2',
    'nnuqqtyzppffwwwnnml 1',
    'nnnsmeeennnkkkoopgrssdddmmmllcmmmbwwwiimmmm 5',
    'jjwiyrppfnndeeejjmmmeeerrrfzzzaaayyyjr 1',
    'hoolllllgggjjffttaiiirrrjjvoociffsmmghhh 2',
    'qjjjtrqeeeodddyyyyyyjjjhhnzzaaatt 2',
    'fffdddjhhcchhbbpggxxxgmmmrrcjjttuuzzzhhhe 2',
    'yyyhhhccssmmhhovvvqqafowwnnjjjwqa 3',
    'qqqiiieeeewaaadsswwzjgwweec 4',
    'tteedppphhhkkkddccuueessxxx 5',
    'fffbmmutttnnhpprrii 4',
    'ttdddffneeewpqqqffrrrwqq 4',
    'bbbuuuyhhhzzzqqqttoorrrpmmjjxxxcc 1',
    'vvvdddppfytxxxpoojjjkkkaaa 4',
    'tmmmrrjjuuuvggaabbhhsssmvvvnnnmmmqqddkkkkkkmeeezlllcl 2',
    'iittlllfffddaawwsssffuuuzyyltteeejzmmjjccdddqqzzzssv 4',
    'uuceeevxpppqhtttgg 2',
    'zkkkiiaabbbbrrrwwwjjjoowwwyyyrqqqky 2',
    'kkgggtttnyykkzissss 4',
    'lllooojjbddxxiiieeemmmhhhtttvgggmmxxhhyyiuuwl 3',
    'hhmmxxxzzqyruullluuuddrrhlpdddvyyyxtzzxsss 2',
    'tcccccmmmpppssspqqdhhiiiizzzqaajooojvcc 3',
    'dddqqqrrqqqgggvvjjpppzzeelbvbblllodddwwkkllwwwhggrr 3',
    'ddkkbfddffeeekeeekkkdddssh 5',
    'iaaassaanrttvvvvggooggiiilll 4',
    'cccflooolllksssyttlttilllsslliiiwllwozzzmm 4',
    'vvqqsssxxqqqooozeeepppjjjaadddsjjaazsssfff 4',
    'fevvnvvkkkbbbfjjjwwwuwwwfbutzzzllrwwwbbb 2',
    'nnnxxiiwwwttqqqgggvvvgssbbyyyllxrzzpppnnnmyzzvvhhh 4',
    'booeccyyuuuffzppkkkmmnnng 4',
    'tttbbvvpfbewuuuaaaxxtheeel 5',
    'mmmnnqqqfffffmyyyzzfffxxeeeffrrrnwwweeeuupppqqqffdfffkkk 2',
    'pprrrpywqqnnnjjjzzdnnrrrssgggr 5',
    'ftttnnniiinndvppzummmvvvkkk 1',
    'yppvvssvddvnpmmmkkmmiiieoozppvylvvggxx 2',
    'wwwwwzgggxxxlujjjeezzzwwssstttjppwwwgu 5',
    'ooeeeaaamnnbbbiqqkkfffjphxxxggeehww 3',
    'jssjjjeeehhyyyttyyyookkreeegghhnntttyyynggdrccct 4',
    'xxvssoooapppclogggmqqqqqaffrrppooddd 4',
    'ppppssafffvpllwgsggxxxwwnnriiuuu 4',
    'nnssfvttxxeeppmmbbb 5',
    'jnnnjjjlkuuubuudpppjjjbbzppcdfmyyhhhyygxl 5',
    'mmddtttzzztlllxkkddwyyooofffaaayyyaaai 2',
    'ecdddwwqquujjjrrxxxeeedddseww 2',
    'aammhiyyttwvddvv 4',
    'ttqqqnnccckkuzjcccqqqvlwwjiiiyyyvjjrrrtussiiifffj 3',
    'dzzyixxsssbbbrrryaatzzzg 4',
    'kksggpcccwwrrrzzgsrrjfbbwjjjaa 1',
    'bbbyyyrrpyspppvvvsssttkkk 1',
    'yyyxsaaavxllleeexxdddmmmxs 2',
    'ooommtttqqqvivvzvvvrjjjbbbenzzzddgggzmmzzukkkrrrsssrrr 4',
    'yyxxttmmttdjdddddzxxxtchaarrrdddvpppmm 2',
    'aaaruujjeegggfqqtthtttppbbnnnssudddrruuxxxjjjqqqcc 5',
    'wwwhfnnngddeeeooonnnaaazvvdddddpbbboooxuuzu 4',
    'swwzyrrppmggffswpggaafffigiiffhhhfffwww 1',
    'ffeeejjggvvsppvvwwaysssmmmxoooffjxvvv 1',
    'qiirrrvvvmuupvvdddbuuufbbnnndd 1',
    'eexxooonnnmttvvlljjbbbxkkk 1',
    'nllmmmhzgqqquuqqqjtt 1',
    'vvrdppprrvcgggssxdooossxvvvssttjbbbeee 2',
    'ttrkkkffnnzeeloommmiiibbjoorbbbhhhssppnnojq 3',
    'fllwwhhhmmqnnvvtttyynnvwwxulllssscccwwwooovifftooo 1',
    'qqqbbkkkssvddgggdtdlllzyuskk 5',
    'uuuutteeooukkkjiiieeetaaaggouuuxqq 2',
    'aaiokmmmqqrllqqhmmmmeeejjjxllfddoooaaaggccciggg 2',
    'piiixxsxfnnnvfjhhnnpppggpppw 1',
    'bbycccmmmxxxslllmmwwbblllvhd 2',
    'wwrfffuugggpttttnooouuuxrmqqqjhf 1',
    'cppddhhhiikkkkkrrkkoooxxxjsccctttwwwtwwr 2',
    'rrqqqppffgttsllsssi 3',
    'jjjbnyyymddmmmuubbbtttvvmddsslllpaawrrrnyysccczzh 1',
    'ssxxxdddnqqqsbboxxuu 5',
    'qqagffkkdddiweejdddxkkkzzhhhuuiiifffffxccc 1',
    'gggrrtttsssymmpwwddvvvyyyeeesswwwrrlljgooolllhhzz 4',
    'ugssqkfzzkkkfffwwqbllzzzwwbbbuuutqdwww 5',
    'ccccgggddhhhnttfffbbboootttpppuuoooll 4',
    'zzzvvnnnnnnvrrnnnnnneeffhhggtttvgggbbkkkjj 3',
    'oaaaoddpppgfwwwuqqzzzlsxxxhhrtttzz 1',
    'qqtttpppeinnnccckkkbyyyplccykkkcsszg 3',
    'eeeobnjjmmxxffammmmccwqqqaa 5',
    'zfffutjjjhhbbbnncjjxyyywwwlwwfsssbkkkffgggg 4',
    'wwwwwnvdddbbwrrveeemmmyfffeee 1',
    'kkkftaaachyirhhgggjaannnjjjfffffflllttt 5',
    'tjjhhhtjgxxxzqqnddddeeettuuxxdddwoooaaaaa 2',
    'pqqquwkempppffyeeeaaakiixx 2',
    'pppemrrilfffcccskkqqqioo 2',
    'dtbbbgpyykkpprrrcccwwlknnnllbmm 3',
    'bhhtttiiigggjccczzzkknnnxxssqqqzzdd 1',
    'uuddemmqqqemmjaaxxxouyyppphcccyyeeettqqdddsc 1',
    'mmmnnlteeefffgghhhjjjtttxxxoooooobxojggkkkgggooovvkvvv 1',
    'xnnnzxccuunnuuujjhhfwwwqqqwwwldddhjjjzffgg 2',
    'ddarrrffoooayyymttnnnqqqxxgjjbeeeczaaffrrr 2',
    'wwvvzttvvwwfffofffaaaaaaccjjvvrrxxmmmzzzeeuuuc 1',
    'yyiiikkkcbbbooooossxxxzzz 1',
    'xxzzfhxxvvsmmmkkqbiikkksnnxxxj 5',
    'pppnvvkkoooaoiyyaaappprnhh 2',
    'aaaaccnnncceemmmxpczzyyybbbgggnnnzaazziinnnruuqqq 1',
    'utttyyccttgggbbbffuuuhhllppckkwwwpppqyyyffkkkaazsn 1',
    'vpppoofffyyymkkkwooguuxxxzziffxxxqqqeeeuuuiiiq 5',
    'sssmmbbbggtttthhhqdnnn 1',
    'eeejjttbbbiiimpppttuuwwxxqaa 1',
    'yyhkkksslsssnjjookkkm 4',
    'fffnnnoonhfffppptveeppoojkyy 3',
    'owwqubzzzjjjeeekkfvvvuppprrnnntttnnnwwczzzyyzzeeezzyyy 2',
    'nnnmmmjkkggllssmmmkkkxoo 2',
    'tomwotccctteeej 3',
    'ccnjjjzzyyxxxhhzssswwwlllyy 4',
    'zzyzzmmmooyyyddtxxiiiqqqqq 2',
    'ceeezappdxxrrrqqqgggkibbffiiiuuuffccdddx 2',
    'kkxbbbxwwwtturrzzznllliieeeutthhheeemmyyyfxxxwwdpp 3',
    'rrrxxxxxxoonneeefffpvaaakcssgggdddfffwwwfhhhrrreeenn 4',
    'nxxfffddxxxiiicpppppaaabmmmddd 4',
    'iiiojjvvvmccclllwcpppzzllzzuuutttiohhmzzz 5',
    'ctttppptxxeaaaffiiaaowwwrrrhh 1',
    'vvvggiyymmooopppxzzsssaalllxxnnhhhpaabbbwwooomm 2',
    'mmyyyjjjweeemkppuuwwqxxwjaffdddk 3',
    'jddcccppwwwgesqqstttlllmmmmqqqccczzzuooo 4',
    'vcccddtwvvvpllxxiixxxjj 4',
    'qeeefxxpppaaaowwseffrrrbnnzffnnnyrqllmm 4',
    'uukkkswebbgbbzzzjppllwww 4',
    'iiggdddiieeebbswwwffosskkkuefzz 1',
    'kvvvwwwgmmmcgvvuurrrqqqqkkyyp 3',
    'aannncciibbgdddaaddttgguurjeg 5',
    'wayyyxxxsobbbnekkjjjrryxqqq 1',
    'qqqzzeggggnnnuuussffkkkiii 3',
    'ddqqqiovvvuutyykkkeellzyyyujjttty 2',
    'mmmccrpybiipprrrgzzuwvuudwwlihhnn 5',
    'afffrrnnllljjjxxxheggqqiiaajjjnnpppkklcddnnyttt 4',
    'oowwwsvvvvvvbbbwwyyylloonnntttddwhttttsssmmppxcu 1',
    'mmmppffoootttlzjjttqqqjjnnnkyyy 5',
    'hhmmmxxllwwwooogdddkkkfffqqqccssglkppffeuuiiirjdss 4',
    'gqqnnwwcccuubbmyyygggtbb 5',
    'pppooorrjjjsjjlzzjjjtgvvvlllzz 4',
    'hhhhieevvvjjttuuuccwbbooorrhhhooozzvvvfffsn 4',
    'aauufrhhzeejvepppjjjttqppnxxx 1',
    'nnnnxpppnnniqiiwwduuuxxx 5',
    'vvvykkxxttacccwwgghdkhnnzzuuuyyyaaassuuu 4',
    'ooornwooysssflluyygvvv 3',
    'qqqaaapppxoooaaazzzxxxkp 4',
    'mmomxxxsssrrrkkkhhhfffmmrrrjhttjjjs 3',
    'jeewwdddqhhqqqqaaxxerrpppjjhhceeqqllffeeeyy 1',
    'sccrraaoofmmmxxly 4',
    'qqqdrrriyyzzzhhokkkanniiirwuuuuwwwcct 4',
    'ccwwwyyggggzzznnnsukqtzggglllqqkkkyffggzzzuuzzggk 3',
    'mmoozzzpppnnngzzggldxxbbbuuusssbbmmcwwooovvvfmmyj 2',
    'uuxxazziiaamnzsssuaahyyyzxrrrjjjwwxxyyy 1',
    'aavvvpppoyyyddsuummoooyyyyuhhrrvkkkhhhqqkkkaaahhh 4',
    'kkgybbzzzioowwwzzllnnnkk 3',
    'yrrannmmmzncccrvbbcccxlllbqqqejjyh 2',
    'eeelllzvvqqxuuusiihhknuuupppttssscjjj 3',
    'pbbppjjoozzgggggssqqq 4',
    'uxykkkjjjrrxwwkbbiiithhffggaaf 3',
    'wwwllliiigggttbbblllpfbbhhhhhwxxiiiiibbr 5',
    'ttaazzzzzzbbggvvmjjjhhrrrttiiimyyuuurnnrwww 3',
    'bbbrrxxxxxkkkccdddmmmmsrrr 3',
    'hhqqqjjrrruqqfffffffeee 3',
    'jjcyyynnbbblllaaxaabbbyybbbtt 2',
    'ssrcigggkkdddnztthoqrrrkrr 2',
    'rkkwrjjjpppxuuvvvrrppzxhhiixkiiivvs 2',
    'wwwiipppttmsssozvvvtvvvzd 1',
    'djuoyykkssqqqfffqoocmrrrtymmmpplllsqqqzz 5',
    'sssnhhxxxnnymbbbxhhhowwwaaffeezzzaddyyykkkuooj 3',
    'gffaxxxxxbxxxmmjjjddqqqvvvpkj 1',
    'vvvpqnnnqqmmiiigggoeeepprrrru 3',
    'qqquukkrrtfffxsnniiirrjjzzkkkwvvvmmmmzcnnnccfgg 1',
    'uhhuuaasspccrrpppk 2',
    'fffgeesowwwbbioooiidd 2',
    'fffiiygggxxcqwwzzzsb 4',
    'vvvpuuzzzobtttdddxxttzz 2',
    'kkkassiidddaahhhwwwxxwwwcccll 3',
    'auuddzzlllyykejjeeekkkkkaassbbb 2',
    'leeucniiizzjjjhhecqnnn 1',
    'yyiwwnnnkkkusssjjjooocwyyyysssggg 4',
    'aaahhhtooozhllljfffbbs 3',
    'jjmkkszzzyymmmkkaafffnejcqjlu 1',
    'rxxjjjffmmqqtttuuusss 4',
    'iicynnnoooooyyuuurrggsggrjww 4',
    'nvffpkuubbssstsssbbbccc 5',
    'llloooqqcccttolrrrvvnnnyyffhhtttrrrpppdojrjjgggggbbe 5',
    'fffvvsszfflllmmmyyjjjmaaawummmotttaaa 2',
    'suvvvffgggssswwukrroorrxxyaaaxxtzzhhhuuuzzzvk 3',
    'yyyddddddreeeuuxxxtbbbdddhmmmzz 5',
    'gggwgggnnhhhhxxxrztttq 2',
    'yyyeeewwwcoooooqqsstttyyppoo 5',
    'jjeiiiepoopppbbxxtttubbajjjqqkkkhgggfaaa 2',
    'ahpppeedvvvnnngggnbbbzzziilllllttt 4',
    'rrrrrrzzzpxxuuuccciidmmlllkkkfjjmrjjrrro 2',
    'rxxpppucrreeebbcllqqqtnnncccddkkoonhhfffhhfzzfffyy 5',
    'jjjqqqfoosssjxxhjjlll 3',
    'yyynnnkddrfzzbbbduuuxxllegdddfkkooollddddddggzzdd 2',
    'qqtnnggppwwwjwddfffiiieddffookkavvvssmmm 3',
    'yyyxxhhggzznnnjjzccqqqukk 3',
    'dddtxxygezzzaaahhmrrrsqpppffaal 4',
    'eewwwviiipfffuuummmkkrrxveeeooobbrleejccddnn 4',
    'ttttsssszzzjjjggaaavvvfffwwbb 5',
    'ggqbbbtteegbbwtttccuujj 3',
    'ccsssfffoooeeexxxiivuuuyydllffftyymmmvvjiii 5',
    'pppuuurhhhhkggginnsuuhh 5',
    'sssqpppyyerrrffwnnnttbbbrr 5',
    'tqqtooouuuhhuuuzzzmmzziihhhbnuulsssqqqwwwpbbnnzzzee 1',
    'dddqqqhhhhhmmdttbzzvvx 5',
    'hhxxxxxtttnnzzcmggzzzigpppinnnfffjjoooxxk 3',
    'zzzsseezzvvvffjjzzqgggrfffzzzzjjjveeuuuhh 5',
    'yyxxmdddykkzzznooocccffgwccciipyyyssnxhhckkkiiigg 4',
    'cxbbzzzpuuxqgggispbbiiiww 2',
    'llohllljjjbbbyyyhaaspppyyqqqummm 2',
    'jjhbbbennngggaaaqqqvvvxxooottqnxxxatci 1',
    'yynnnitaaannpwooddiivveeejjjtttaaaqqnnndjjjdddmmm 4',
    'fffhhqqwwzuwwwwgggcccmmmkkkbwwweewr 5',
    'yzzppddvuurrrrrxxxffaaaggllm 4',
    'ppzzzbgggkkkllaaoer 2',
    'qqqqttdeenxxxdkklccckkkfffddjj 5',
    'qqqycxttvvvlllmmuutttkkkbbacxxxeee 1',
    'diiibbuuuzzzgggwwkokknnnyyyhhhjjji 5',
    'ajddokkmmaaarryyagggimmmaaaaa 4',
    'aakkaaxzzzkkkmmruuusssqqqrrkqq 5',
    'qqqllldddnnnbbpppibkkkcqqobbbjjjjjjxfffkkllhvvvve 2',
    'sfffrrrteaakkiieennhycciiihhhmmmgjbbbjjjeeqqbbg 3',
    'lllffflllkkkkjjjoyllssaakkfjjmm 2',
    'yybsshhkkxaallloomuudlgglllddhhqqjjjllhhhaaancccd 3',
    'nnnysitttggoollooocccsss 1',
    'zzmmmggtffoooyyynrriiwwfmeepjowmmykkdggpp 5',
    'pppjdrgvvnuhjmmmooxxxqcccexxxiii 3',
    'lggkkkvvqqaaaeiiiwuunnbbdddllfffddqqppplvvvvvvllooeppp 2',
    'kktttxxdddfffkkhhhkoobbbhhhmmm 3',
    'uqqkkklflppqqqqqqkkkoonnvvvnnxxbblliiijjrrrlllmmmp 2',
    'eeeennnbuygdvydd 1',
    'ddlllxxxhhqqfffvvvffsssmmmzifffffffhhhvv 5',
    'rrzzzmmmiwwyyyhhiiizzyyytttcc 5',
    'iiigxxxpwwwggdssswwwzziiizzzvvvliiooooddooowww 5',
    'ssoeefzzzpppyykknnnlddkjruuuaaummmxxtttdpp 2',
    'uuunnntttccmmmtttccborjssskkktttzzzooohhhnnnff 5',
    'zrrrgtttssstttgggwjjjrrr 2',
    'fffccyyeevlljjjddpjyxx 1',
    'ttseeeikvvvwoomyyxxlllkyyypipphgggggwwwooiix 4',
    'cctfffbbbdddxeeettvjjh 1',
    'nnnddsdbpppuuuzzzaaaaajsssd 4',
    'bblllgggvvxccfffxxhhhdggbbuzyy 5',
    'dddeeeuullsvvuhlqqkkkjjjzzzssctttb 2',
    'lllrrrzzzqqiiiwwupcccqqqho 5',
    'nnndddrbbbiirrrbdddbuuuttuudddpp 3',
    'aaaprrrrrfffoolllrgwwwwcceegllh 5',
    'pmmmfffoocccfffxkkaaavvvzzyyygmffvvjj 5',
    'uusssesssmmmbtvhhnbmmmggpaaazztrhhpccs 5',
    'hhhrrrbjjjfffztttnnrrzqeee 5',
    'laakkkuiiillqqfddeeexxbmmdddaggsssoopppeem 1',
    'ccccxxhhhxxxdrrrqaawwgrpppuuk 3',
    'pyyyuuuuppppdddddrrreezzyyammjoooyqquuaaawppzzkkl 4',
    'paaacccmmaooonkkkmmqqq 1',
    'qqqvvvuupppxxhdeaanbbronnnnuuuiiwwwyyyeeii 3',
    'zsiiikkkivvhhiaaaeeekyppzzlwjqqqjxyyyxxaa 1',
    'wdddxxnnnaqqyylloossshvjkk 2',
    'afffidddnnncuuuuuussqqqqqqqaa 3',
    'abbbyyijjyyydddyyymmmhjxrrrpjoooiijhhhmtttzznnnwwwaaa 3',
    'cccccllggguuuwwxxssscpxxl 1',
    'rrrvvvsssbblllnngajhhhaaacccdd 4',
    'hbbbjjjttzqvvvuuuuunnnxmmmxxx 5',
    'nnnerrrvvqqaaakktttppplliyyiiisxxqqmiimmmrbbbqqqss 5',
    'nnnqhxxmmzzzkzuuubbccc 4',
    'vppluaajjjiiaaarrqqqaayyrrrnnnvmmmxxxf 2',
    'ddzztttfhhhllvvvursuuussssllluoolllgd 3',
    'rrrzaolllnnqqiirygggiinnyynepcd 5',
    'ydmmmdzzeeezzzaaapppbbjjv 4',
    'msssdmmddffnssjhhhk 5',
    'bwwwdddssyyffrrrssoooxxxaahhhoozzziiiissccjjjccsy 2',
    'bbbpuppcccxjjjaayyyvkssgggsssrbbhhjj 2',
    'uujjyyvdoeggrrrrrx 2',
    'cmsssyyoovvbbzzzbeyyyffnnnrrrpzlllznnnlttaaaqq 3',
    'llpppzfeeeqijjlllldnmmnnuuwwssiikmmm 1',
    'ydyjjjiiigggvvddiissiyyiiixxyiiilm 2',
    'ccssrrrlllvvvllecwwwooovvdddgguuupnyyttteexxt 1',
    'nnnuuullllwhhhybbbnnaeee 3',
    'llfzzlltttfwwqqqxxxaannk 3',
    'iiswwfffcccirooojjsssufffvvlll 3',
    'hhhggggqxxttteeaiiijj 2',
    'zzhbbiikkppvvviiiyyyfftttbbboyyhhheeezzggeeejbbbnhhww 3',
    'cczzzmmmncprrroeezpppyyyi 5',
    'ppdddiirrrsssmmmyyyxxyll 5',
    'eeaaayyypppzzzjjjqqyyyvvlzzkkqqqwmooppptt 1',
    'vsfvvsssshhyddvsssmkkxxxcttnbbbuuddm 1',
    'iibbkdlcccayylllgzh 1',
    'uudrccccqqnnccyppa 4',
    'hhhmmmooorrvvffkkkjdddxpppzrrggoorrrayyypppy 2',
    'wwwpppwwwxxxjjiirrccjjjnneeemohhssscrrg 4',
    'pppttulllwiivkkkhhhoogziiiaalbbttnnyyyvccpp 5',
    'aaoohhgzzzmmmnvmmzzqqq 2',
    'hmtdhhhqqgggxxxyn 5',
    'phhhbbbuuuuuwwkkukkqqgggmmydohhtttoos 4',
    'yyyttnmmmrrrxeewwzzeeeynuuppaaaivzzssmi 1',
    'rrrzzzppnnnpppsnbbbggnvllllsddduxvv 4',
    'sssdoodddbbbvvvonriiikaaa 5',
    'eeecgsxxdrrzhhhccxxhhhwwvvvwwlppzzuaw 5',
    'ppffxxxxkkkxxxxbbimlllmgbbijjjcccojwwwfjrrut 2',
    'eeeoooeeeoouuxxxppprrrbnnnsjxggvvvcummmvvee 5',
    'kknnelllssvccchgggb 1',
    'feeeuuuullkkkszvdddvvoxxxooyygfffccbbblllmmmdddhhh 1',
    'aaaaaaiiimmmzzzwwwttthvvqqnnmm 2',
    'uuujrvvvohhhrrriiimmnnwwwzrtttm 2',
    'hhaqqkkkooowwwooojjnxxqqqssslppphhhxxw 5',
    'dddwfuiirrrdkeedeelllkkjjwee 2',
    'ffyymxxvvseeejjjttmmpppzifyyyllljssiyrrrhhhrrrscc 5',
    'brrdddyyypppjjjeettyyyzzzurrzzyyrrrcc 3',
    'pnldddpsahhhaassstttzzppbdddwwvvvqzkkttnnpp 2',
    'rrrcccxxjjkpphyggblyvvvibbppplxyyvwhhhzz 5',
    'tryafffvisstrovvvzzzzxxzzzfffeeeaeeebb 2',
    'wwjozkkkyyyqqqssstttggyiiwwlllgggsskkkbbbwlllbbbhhwyy 2',
    'uvqxdqqjjyyyzzzggkkzzvjjcgg 2',
    'ssmaagggdjjlzziiiggo 3',
    'uuffhuuurrrgyyyaaaikkkzffuztxxxlll 5',
    'yennnetaaakkkyyeeykkzzzzzzzzzdiiffll 5',
    'hhmuuuiixrhhwweeeyjjyyuvvjyccc 3',
    'ivvvizqqhbbzznnbnnzzzccckkllnntt 3',
    'oddjlllqqllkqqxbdddbbcccdddttlll 4',
    'ttvvvuuqqyggggtttqqqgggvvv 3',
    'wwlffffayyyggttnnvvtdddrrmnnlllmmjgdcklll 1',
    'pppinnssuuubcfffwwwtppppppttmmmiiiwwwgghhhqxxxxx 2',
    'ttttuurrpwkkkwwlllqqppmmm 3',
    'hqffqumbcgqqqnnkkku 2',
    'kkkiiiiiicccnnnttwjhhhllllyyybkkjjjddduuuaavvvapp 1',
    'bbxcckkktwwxxhhbgjjhhhzziikrrr 4',
    'cccttruujmeeddaauuuhhhwwwrrcaaa 2',
    'tttrmryyygwwwcccxxiiiezzzgeeecaannnqrruuujjjowttt 3',
    'wwwyybbudddttqqylcccooodpppkkaa 5',
    'pphxaaahhffflccbbbxxxllllloooruuudaaa 3',
    'dqqkkkbnooeeeyyydddpjttthhhjqqwwww 4',
    'oocccrruufxxooovvvppqbbbjxxxwwziiuuiqqqqqqyxxoh 2',
    'jjgggmmffftjjmmgghlllhhekknnnkkkzeeolllyyyqq 1',
    'ddnggxxxiiicayyyllhhgwlvvehbbblyyygglxxbbxxx 5',
    'bjjfffnnmxxxxllrrriiiullbbtt 5',
    'wwqqqhhhnkrrsjjjffzzzvtttxxtkkktteeeeee 5',
    'juuubddhhdiiiqqqddussfpooovtxxddwwkkkcccddppp 4',
    'ttjwhhffflgggxxxckkxommmccttt 3',
    'dddjxxoootttaaaxxxcckkdjjyyheeeaagiijrwwwsssqlll 5',
    'yypjjfffttgggtwwqqqbbyyyknnuubbb 3',
    'ddjsssqwwddiiiqqdvvvkkzccceilrrrdddnnhox 1',
    'ppcjjqqqjcdhhpppddqqdddww 5',
    'ggghhhjjjdddhhhzzooccaayeeeaaa 3',
    'hwrwwuuygggeeqqqqyyhhbiii 5',
    'wldggqqqyyymmmdxzznaaddiir 2',
    'eecciiixmmpgggunnnjjdfuuvvvkkk 2',
    'jjlllqlaaavvvnnnnnnihhh 2',
    'jyppcccjppfzzzdxxffxllqq 4',
    'qqmmmxaaaggkkcccbbixvvhhkklkzzxxxssaabrmcuuu 2',
    'zzzllidddddukaannnfffll 2',
    'ojjjmjjrrottsqqqlll 3',
    'uupvvpllljfffkkkooofffygbjjjjwwwyyyeeeaattooi 1',
    'rrrfwpprrrutttttffjfffppbbbnnnhhhuuzz 5',
    'hhhiiiyyyykkkcccpphhhqqqcggffftep 4',
    'wwmmtyyaannnaarrvvcccsddcxxzzemmmwwkkkllssggdd 1',
    'obbhoariiiiivvuuggpppattgg 3',
    'bbllpppppzssydmmmrrvzzzawwwjjjoooeee 3',
    'aatttarrrcyssbbbqqlllmmbb 4',
    'nnnrqqddeerniiiym 1',
    'nqhwbbbwwwvvvhttxxeyyyrrr 2',
    'addzzqqmmmgggkkvvveeeoooqciiihhhooii 1',
    'zgxxoofffgggooofgaxxxhhhpoorrtttlniitttuuuib 2',
    'zzzhmmmllfffddxxxhhrrrqqssscttnnrrccclllgggrrre 5',
    'rreeeizxxeyoggfffyyydddccaaahhhiiiuuaaommyyyrrr 2',
    'ppprrrlllsggyyaaattjjjjjjdhhhgggddbffxxtthhhfffiiiff 3',
    'affeeevwwwrruutcccttkkkkkzzppp 3',
    'mppqqqorrrcccrrjjoccjppriiewwnniihiiieexxtt 4',
    'nkkiiiuueeiiizzynneeerrrdddpppcccjeee 3',
    'wwwjjiooogggxxpprrtttywwwnnyyynhhh 1',
    'yiitttccyyyvvxxssshhhyyyooyuuubbbrrrqq 5',
    'ccoooibbwwwllnaaarzzvvvffuvvaogtfggtttqqqqiiff 1',
    'kkqqqooolmmttcccsxvvvsssyyhhheeeccczzzarrvv 3',
    'eesppwwttyymmmezzzbbccaavverwiiimej 4',
    'yyyllooxxxcccwwmyyhssseeeqqttpqqxxxqq 5',
    'zmzzzbrrrllkkiifdddpwwwh 5',
    'ffftjelnnccchhccbbbss 1',
    'ffzzzllleeewwwuuzgccwweeexoo 4',
    'oovdggguuufffcczzoohhssooobccccc 1',
    'ddvvtttieemmmmmmllttttleeettbbbmmmnhddaajjnuppkkkbbb 1',
    'dttxmmmmmxxlllwwwllttaaateeenyyoouueeewww 3',
    'ffxsyyyaaaoooabbbmmmhhddixxxeeelhh 5',
    'rnywwwlgfgggkkeeemmmjoouaaau 1',
    'sddvpppsssvvvuufdddjjjwwzzz 2',
    'wrrrcckkzzzddyypppkkknwwhhheerrccgggzmmqwwwxx 4',
    'rrrbbbhhjjggoewwwiiiixxxpppxxxmmpppflllsssjfqqqomm 5',
    'xzzzwdddvvvtuyywwwppxr 3',
    'xaalllujaaanuggccqbbnnggguuuii 2',
    'uffmmmmeepppooxxxeeejjkkszzzooffpppggttxxj 4',
    'aaaassdmmmbbccmmmnnmmaaag 2',
    'lllwoouwwwbbbrrrssnnqqqtzzzvvqqvmmwwwkkkmmnpstttc 5',
    'yyxxxkttwwwgrrccjjyyyiihhphhbssjj 3',
    'jjjjjjfzdnnncczzjjnncsfdddeii 5',
    'sffeddggghhhswwwdlliiiassqqqhbbbffwwwsxxsshhwwwffaa 3',
    'ftttskkggwtoouuweeebbilllaaajjsso 4',
    'tsxxxjjjgggcccjxxdvreeecge 5',
    'ccffbbeeevvvnnuxxxpppwwwxedgggrrrwsuooiiizzbwvvc 2',
    'bbbmmmqlssbbooeeeuuuhhhcppprrrhhhvvvbbbttroootrggddhh 4',
    'jppwwwqqqmmyyyddhtttmmngbbbb 3',
    'eeoxxxtttiipbbrrmzzzdjjjllleyyypppkktttmmmffmmmhhhoo 5',
    'ejhsssrrrajjjwwysvsseekktteebbgyyypxxxk 1',
    'wbbbddggmmjjjcccpjjlllzzzkkkossu 3',
    'arruuujjjacigggrraaeeccxwwuuoovvvkkmmaaannsassz 3',
    'dbbbeeetttqqqeeebbbvvvidddwggguuqiiexxxngjjjdfffssp 5',
    'nrlaaattttttvvkkuupplllhhhioliii 1',
    'eetwwnnnjjbbittaaarrjj 1',
    'uuussspppoodddsshhuzzzoiikymmyyqhhxxx 4',
    'dddzhjjjlrrrczzzxxtyyy 2',
    'mmbqqqhhxyykmlciiccqqxxx 1',
    'ixxwwwaaasssfeeejjjjmmmpzzzozwwwreezzzg 4',
    'rnnuuuyyhiilrrrfffeefwwjjmqqyyyaacchxxx 1',
    'ppphhnnuuhyyybaarrdddpfffyzzzlllpsssgggxxiqdsssv 3',
    'nnpkkuqqkxnsszzzuxxcccdddaaaeenne 4',
    'wwxxxnvvxxdddnqliiza 4',
    'hhllyiiitttxxxmbbuuvvjjdddkkkppcooozzz 2',
    'dvrrrlllbjjqtttqqqqqqbbbxxjjjggttjjddd 2',
    'zzqmffklllkklllftjvehhhggvznnnooo 2',
    'xxvvvtttttwwqjjfgggaaayynnpaaaa 3',
    'hhhvvvxxjzzzvvtttbbtnmmmaalgggooolwwwoybffqaaa 1',
    'ttrsssddiisngggjewwwwwwqeeaanmleeg 3',
    'fffvvvqquusunnnkkjjjxxxcrrdxxfffxx 2',
    'tthccllzzjjcvvvkkxxeee 1',
    'nnqlleeerrrrraaajjggnnkk 5',
    'kkkeeerrfffqqqrrlvvlllwoowwwdddkkznnnnnwwwwwcimm 3',
    'nnndddwwcccvvguuhhtttxxllkrrrkkttiiixxcrrlllkk 3',
    'uxxqqjjjuuutxxxzzkkaaaaoookhhhrrrbppp 1',
    'tttvvvpppoirsooovvdd 1',
    'wwddpppuuuqqqqqxxxpppuetttthhhhhyyygvvuuuiiwwippiiggf 2',
    'aaayyyffoommddiieeekkknnuuuddjjwweeevvptuhhbbb 5',
    'vvnrreeeiiipppaiiaaqwwweeefffbbblllcccjuuupppbbbbbttnncccoo 2',
    'udddruucccitfffooosssgppeeeprbbbvvv 5',
    'uruuulllttmmmkkpntrrrglpptttccnnqqqrrrggddfh 1',
    'gqquunnnkklnmecctttlllgaaiiimmmsnnttiiiiiio 2',
    'xxxwgvvvuucccllllllyykkkwlabbaacxxxusswwlln 5',
    'bbbnnngggsjjjdddnnmmmcccxwnnniiifdddllttpp 3',
    'hyyjjjnnnjjnnnqvvyyyrcsstddandbblltggddd 5',
    'itofdjjxxxttookkkhiijmhhllwllttkkkssfaa 4',
    'bbuuutttffzzwwkkeyyyfffkkllxlkkgggllooocccfff 2',
    'ttccmmqqqllccqqnnnbbk 2',
    'jjjssbtjjiiddwwwcllqqqphhnn 3',
    'nennaawwiiihwwaazzzssstttvvhhaammzzccckkkxxj 3',
    'gggwwwuwbbzsseeewwwejjvvc 1',
    'oyyyyyyyyjlppvvvzzuooo 2',
    'mmallloooifffhuuuvvvjjkkkfeeiiooodddooohhyyy 2',
    'nnttjjllyyollwwtttdvvllydpppsemmm 1',
    'ccllyyyjbbbxmyyygpjoozwwwggnnpppaookkvvvxxmmmmj 1',
    'uuuvvvddgaavvrmmmqqqhhh 1',
    'uuuybbbqqqtrkizzzttkfxxxatttztttqrrrnnnfxaasx 5',
    'otttkvvvpezhhvvhhh 5',
    'zuoootjjjrrropppwccffkkccce 3',
    'mmmeeexxxbbbpppkkyyyedxjrrmm 3',
    'qqqjjjzhhhtttqqbbbbuuueeemiixtt 1',
    'lllqqqgffssshhhvvvwwwnbbbqqir 3',
    'ssseeegcgguiiuuudlllii 2',
    'qqxxxccmmmaaayyjggmvvvfffyypplllrrddhhnkkkrq 2',
    'uuyyaaakkklllhhhbbbzqqhhhvvvaattt 4',
    'bbbyyynvvvgggkkmmmtttfuqqvveeddxnnnkksssvveevvvzdd 4',
    'ttppovvvqqmmqqbbbuyyyzzzc 1',
    'zktyyyppfffnnddfffllltkkkuuumxjjjyyykkttkcccvjqq 1',
    'yyyuuuzzyypmmluuusssddyyyrrrpggqqnnzzzcczzzbzzzyy 2',
    'pmmmzzellbpppaytttcc 3',
    'vvvyyvvddyyyppxiiinnngggfffjjjgglleeehhhhzppuuuuuurwweevvv 3',
    'ddkaaaudddyyzzzawwqqhh 1',
    'uuiiincccddjmmfyyyj 4',
    'rruussuuaauuuxxxhhyyybbeabbbzzlfffrryymjjexxxkkoo 5',
    'dddzzzjjjqqcccffkkfffwyyyttvvvbgggrrroohhzzzrrrjjj 3',
    'wwwlllnxeaaajjjjnnnccmaaazjeeesssqqtttvvv 4',
    'wwxrrtttxgggootthhnnnjjtti 4',
    'mmmoppeeessaawwwbbbiiiyylllssshheeeatvvmmmzzd 5',
    'innwwvvkkkwwwaasyyxaaak 5',
    'nmjjjggtiiihhggfwwccbhhffeeeffgggrrrlljjjwwjjjgg 2',
    'uuuutttvommmuusggbbcccjjj 2',
    'wwwnsrroovnjjjtoztaahhhyyttwhwtffll 3',
    'huyyfffhhhkkkrakkxkkgglxxxpppttrsssyyjrrlpjj 1',
    'oouuullliiiiitfqgveqqqbwwlqqteexxxa 4',
    'xoiieekkahhhqqqqqhhyyy 3',
    'tttiiisssaagssstbbbddxxxb 3',
    'aajjmmmeeeeldddzznc 4',
    'yyyzzmmdmmmowwwfffwwekkivseeexrr 5',
    'eewwwrrrfffmqqwwbxxtkkkbb 3',
    'ggddueggvvheeeeeppooqqfpcckknnppeeessookk 5',
    'uulvvvzccciffcvvtttllhsww 4',
    'dddmmmcciivpppnnnnkkkuuggggggfffvgdyyyookkiiiii 2',
    'jvvhhorsssrrvggd 1',
    'alllgggwwgglmmvvvttbbbbbb 4',
    'xxxummmbmmccdddvyyyyyvvvqqqezmaa 5',
    'sssdpaaakkkpppccccccffff 3',
    'xcxxiiiyyvhhhhheeijvvvozwwiiittvfffgkkmmm 3',
    'qqqxlbhhhzzmmmuuummzzqqb 4',
    'uulzznnkkbbbmmoooiiijuwwwkkkdddddmmmmmallrrrddxxxoovff 5',
    'ttvvgtthhhddarrrrsn 4',
    'qllljjrxxgttxxxddkkkeepp 4',
    'xxxrrrjjjdddrrrzzqqtaaammmcv 5',
    'pphwwwmmmxxwwffkkqiiddbbbbbggeepppkkkqqiii 4',
    'xfffoalliiqqqrrrdww 4',
    'sssexxdddwzzzaacceeerrruuurhhzzppl 1',
    'vrrrddllllccddaaaqmmvvvgggixxckkwwwwuuusvvvs 2',
    'eeggmmrrhqqqxxfffssuxf 4',
    'fqzzzggimmmsiidddbmidlyyyhxxxzzl 2',
    'rwzzzfffggaaileeg 5',
    'mihvvmdddvvzqqwwwx 5',
    'nnyyymmmppdxxmmiiikeee 5',
    'oooqqgggxxssrrrmmmmfffiiiiiuukkklllnngppfiiiuwww 3',
    'iimmsssbbbuuutwrrrpppddeee 5',
    'ddpppqnnnwouuuolgg 4',
    'lllrrrsaaauuvvvsiiiiiittxxccuaauuiiiaaafqqkkkwwweee 1',
    'lhhlllnnnbkkkrrrkkeeeilcwwwjjvvv 3',
    'mmecooopssszzzbyyymmvrrsyytttppnnnqffflldddggrr 1',
    'accccbbbdbbaauubxxdddbbmmmpp 3',
    'kaaccwfffbfffkkkspppguu 5',
    'grroohqqwwvvveaafffyyjjqqqqqwwwllqvvkkktttppcffmwww 3',
    'ikkkpffsswwxxxeyygghhhn 4',
    'rbgrrruuucccwwweddjjjsssllccwwkvvsssryyaaa 1',
    'ggffhhhxxxxxxiinnnvvzwwqqqxxxeeegggfffcccffkooodddhh 3',
    'tttrrrslennnqnnnnnafrwwwzzznudddxjjjjctbbbruu 4',
    'llltttmmmyvvvejjhhmizzz 4',
    'wwwooeaaauuussszzzvvvfmmzzccooomkkkhhhuuooot 3',
    'fxxzteeeofffaazzzttmjjj 3',
    'vvveeewwhhvvvsssmvvrrbfftttwwrrrssnoc 1',
    'mmjjjooorrryyypvdkyyvvlnnnrrrjjjaatff 4',
    'pbdddppiiiqqpppmmxuupbwwmmmccciibjjdvvzznnnyyk 2',
    'nnnvvveeexxmqhhowzzzooxxssszzxaaadffrrdddimqn 2',
    'yyyzzzzzzppcccbzzzkkrrrvvppppvvqquooollpthhhlll 2',
    'bbbzzrrrwoooeiiefplkkkfff 1',
    'oooveeesssiibbbyyiiifffggobll 5',
    'sswrrdddjnyygdjjjwvx 4',
    'vjjqqqivzettjfcgggoooqqqnttlloommkkbpppp 5',
    'llvvvvdiiiwwwxxyykgllaaaawwwqqeee 2',
    'btttuqqiijkkvvvyywmmrrfffkkvvvnnroooihvrrooovvvv 2',
    'bbeeennnwwxbbbbbyasooiii 5',
    'vcccdyyjjbwwqqqppxxxrrqqqzzssllddddddiuujjjqqccchhh 3',
    'ctttyyyqqayhiooiidkks 3',
    'llmmqqqggxxxyyyxedddqqqsshhpphhh 5',
    'aatttyyaaassgaawwjjcccaffnnnovvv 5',
    'jlzzeeuuuggcccaaagggvvcchhhhhhiffdqqq 2',
    'phhttdddddxxtttnnmzzfffcomccrrrrrqqqmmjqhhbb 4',
    'xxvssxiooummooobaaaeeww 2',
    'ssyyrrrmmmbbbggqqnnkcuuuxh 1',
    'uqjjjllssymmmyymyokkkqqqnnq 3',
    'tttecuuugggszzzpeuuvvvmmme 3',
    'zzzosssxwwggoozzvvggdgggjjmmrr 3',
    'jjicccyscfffmxxxbtttdttuccccsgggiii 2',
    'aaaeejjbopvggyiiyyyfjjjvcxxqdkkknaaazzznnrr 5',
    'hlyyyllleeewccwwwgzymmoooqhhh 4',
    'ccwnjjjnhhhooorrrqqqfrppp 2',
    'ttgghhhszzelllnyyypppbbaaa 1',
    'xhhhhaeuugatzdddhhhhddxsoovvvggqqqqqqeetthyy 5',
    'heirrysaaeeekppp 5',
    'bbeqgggpppppjjjnnhzzzpppig 5',
    'bbhhbbbiijjoooegsssvvrrrtae 2',
    'lpppxxxtajiinbbbfffyreeedddbbbsssk 3',
    'eevvviiisqqlllmmmhhunnnkkkxaaiskfffccc 3',
    'crijmnnllqljjjlrossvvvkkeddhlllhhnvvoooe 4',
    'fffyyuvnrnnnhhwvvvwxxxyyyixxxgaakkmmmffjjmuk 3',
    'eekwxxvvtvffwwwdddffyyywwbbzddbbbffffff 5',
    'rrrkkqnuuulpppllxxxwwwtttzzbbgghhheepppblaa 2',
    'ggxxaaxssdddeeuwwwjvvlllxreeqqqocukkix 2',
    'oopppvvvelyyiubbqqqppj 3',
    'sssggrsjjjcllrrcccsqqvvvbhssn 2',
    'ozzznnjhhhxxxffiddii 4',
    'bbuuzkknnnbbxqxnllyyrrzxxkk 5',
    'yyjjjggdddkkkvvpppnysxxcdddddmhh 3',
    'vvxxzzjnnuuuucccufffzzteeelxxswq 3',
    'iddeddkkcjjjdnnoolllqqqeeeaaagggwew 1',
    'kkkgggryyyjjdddfdhxx 2',
    'luuuaggvvsvdfnn 4',
    'hhhyyhhquukkkcbqqbbbiillpppwwwii 2',
    'aaayyyfffgggdddzzllffyddwwwzzfffrroozz 5',
    'llliiioxvvvyyuutiiihmyyhhhzzzzzfyyrrsssn 3',
    'gggjcgggrppupppjdddrwwr 3',
    'bbffffffbbbjjjrutttbbbacccmmmyyttnnnvvvuuu 5',
    'gnnrrryyhhhafjuueeejjjfffuuuxxcccvviiippw 5',
    'bbbypppjqqleeggjjxyeeevhhhubbb 3',
    'vvjjjhhhauullkyadssnnnqqqciiihhnnnocccjjj 2',
    'oaaddddddqqnnoeejiiiiiitrrjjjxxxrrrnaaanwll 4',
    'gssqtttzzzjbbeeeooyyyjjmvvhhh 1',
    'ffkkktttqqqrsvhhhwwrrrppooxxk 1',
    'hhllliiippiiibbbfffyyppooouaaxx 3',
    'ddzzzszgggcmmmwwyyykkwwwzziiirrnnnccc 4',
    'iiooolllfqqadddmmmmaaapyyyxxxyybbbkkzzzkkue 1',
    'pppwwaaaqqqynnzppbbbyyeeehxxxyyy 1',
    'mmdddeeeeekkkaavvvwwwsssooosnnnim 2',
    'ccnyyyqqqmettcrbnwwwllxoooxxxwxxrwwwgggtssssss 5',
    'eoooiiimmzzzkkkwwmooyyypppxesfffbbbooottuuu 3',
    'eyqaaacccbbbtthhkknnl 5',
    'wwwwwrrrwpppwnzzzeueejygghnnnsssjveeexxa 2',
    'lliissstpnnniiiqqooyyyercvywwwkkprmmmzzuuu 3',
    'wwtttiiihhhuuuyyyfffwwhpplssseeuuuxdhfeeeuuuhhhjj 4',
    'xttvwwwmmjjooonnnbbbuuuedfffoolllggghhhstttwwtm 2',
    'xpphhheeoodiiibbbbbyyaarrrhdddkkddduuddd 4',
    'ccczzpgghhhbbvdddkkkttyym 5',
    'fffskkkffoopprryaaaollloiiqqckkqqqqqeepppvvvehh 2',
    'hhhaqrqeeeffkqmmmpppp 1',
    'aazsthhhxvgdduuunbbblljjgggssbbbnnnww 1',
    'ssswwwggyyydduhwwwgggqrrrfffhhhiiyyykkkwwwzzffqcccjjjbbb 4',
    'kxxccouzahhhwwwyzzziii 2',
    'xxxzzzeeellpppiiidfffpppjnnnwb 3',
    'lccuccxxxyybbuuuoooffvvvaaahpppppvvnn 1',
    'hhhwwhhhmocccrbboz 4',
    'mmmooooooyytteyggdddbbbwnnnyyyjjzzzddd 4',
    'eeeyyxxvkllqqzzkkbbyyiiagaarrrttxrhiii 4',
    'vvvtjlitttyyyeeeqqqooobkff 1',
    'jjbqqqppmmtttoooycwbvk 5',
    'cjjjmmmbbuddqqqkyyvtggvv 3',
    'fssofffttdddceekzzaaatttqgguu 2',
    'iiiwwwqqqagggnnuuudddavqqqsxxnnnssshhqquuuttrrxxx 5',
    'deggghzzzfffkkkbbbaammmss 2',
    'xxxooottaaaoopcnwwrriizwwjjjrrr 4',
    'vvvffdddsyywxxxzrwrjjjxwtx 4',
    'xgggkkjjjbbjooccsshhxxkkddvvoojiiiyyyqqiii 1',
    'hwwwpppxxaxlsssmmvvdxprrjppnnjjnnnuuvvveeebb 3',
    'tggsvwayyyaaawiijjeee 5',
    'bmaaappvvpppaarqzzppcceehhhtttlllxxnnnvavvvxfffrrrb 5',
    'svapxxxeeekjjjxxss 5',
    'ddqcllccccooozzhhhhhe 1',
    'vvdtttdddqlllxooyyyxpppejvvvbt 2',
    'jjjaaamgoooyddsshyssrrxxxbbyy 5',
    'ndddaaawwmmmaaabkyyysqqrkkkqbbbxxxzubb 1',
    'oooiiifffjjnibbbcrrrrfff 3',
    'qrrrkkkllhhhxxlllmmmcssfhffflldnneee 5',
    'mmmhhbbbgggttthhhvyykkqqqxxeeettnnncccwjjbqqqppp 1',
    'aaannrrkkpppbbzzmmqqqzhhffcppplll 1',
    'ooppwzdhhziwhhhrrrrrry 2',
    'ppqqqvipzqciiuuefffbxxxoojjj 2',
    'pyyyzxggllssoehhnnnymmmzzagmcccooowwwg 2',
    'mmnnfxxxllmmmnnxuooxxxtttbbbwwwrryyvvalluutrrrzp 4',
    'ooollaaathddzeeezzzgssshhnnnnlllsludhh 4',
    'bsssqqqbbddnbbzzzyyybbbbiibavzyyylllnnxuuuvvww 4',
    'evjtbzzzzsduffefffjsszzqqqzzzssnggvuuu 5',
    'bvkkkddttyyyhhqqqjjjqqoooddlssffuuvvvphhvvvppttttt 5',
    'sszzzvuuupmmmcuvjjjjxxxqqq 2',
    'ggkbblimmxwlllrrjjtttjjayylbbbwwee 4',
    'gghhhdddbbbmmvvgggaaalljaaaxxxavvrrzz 4',
    'ryfvvvroomveehhuuueeepwwpppstzzzggtt 5',
    'nnqooohhhllfffhixxxssrrxxhlllsss 2',
    'kkuuuyydddbbblvpppfffpptttxxxfbb 1',
    'vvffgwwdvvrrrkkiiibgcyyydyyykkktttccccdddiooobb 2',
    'mmmgvvvcdbbbqqqmmuummmttthhttaawwggqqlll 5',
    'aacccdcccrnoaaammmmmmccmmmfffpppdddeewwwh 3',
    'jhhhxhhhyyyxxxavggrr 5',
    'wwwbbbnnzqqqxxbbbcswbcctrryyydddsgggxxxhhhllaaaxxmmhhh 5',
    'cccyyhheeedddvhhefmqggffddimmjjjyynn 1',
    'bbxxmmqqrrrbfbbmfffabbwwwhbbiiivuumnukkkqqq 4',
    'mzzzvvvzppppbbbjjuaaaoocccpplbbbzzwd 3',
    'rrbbnffftttrrgggvvvrrrahbbbnnipppoovv 3',
    'ssszzztttxxxlllnngwddffoppsssbbnnuuuuuowmmmz 3',
    'fqgrrlllpppjjjdddeehhhttt 3',
    'hhhooojlldapdwwwklllmccswwwaa 5',
    'naaazzrrrqqfffxpxxvvbbbyyytmmmllzzz 5',
    'ggqqqaeeeisssoafuu 5',
    'wwweecczziiisyyyeeeqcccwwmmllqquutmmmvvvrrrnnnxxxeee 5',
    'aaagqqqqqmaaaabhhhmmmoosssqqyyfttddppeeezkkkccj 2',
    'aaolrwwffccddeeelooiialllqsmmfnn 2',
    'hovvvkkzzdddttwwgyyyccciittiii 4',
    'mmmsswwwbbbqqqglllzmuuueeeddvcccii 1',
    'ttsfffiilllccmmpudddwwuehhheeexxxzzzeeeyyrrrsgg 3',
    'yypppbbbooggzipwwwttggbbbxsssvmvvvgggpppzkfffjrrryyy 3',
    'oiiioooklfwwubbbzzvvvciiikkkkaaallzzzvmmwwwsss 5',
    'ddjjrjssszzzzcccreeeoouupvvrrvvv 3',
    'xxbchhhzzyyyycccooorrr 2',
    'nnnyyyzzzssfffssvvveeexxoojjp 5',
    'jjjzzyyffwwiiihwwweeeppzzzoossddzzzaakkkhooeqeeerrrggg 3',
    'zzzrrhhhudduuwwwmmmkkkkeeyyybeeeywwmozzzz 1',
    'ymmmiiwwwyynnghllldddyyymmmmzzzwxxxdddjjjiippqqcccvvvmuu 3',
    'awxnnppuppfffuuttpqqqppwwwwss 4',
    'pppglkkkfffcoonnwjoobfyyvaav 3',
    'cwpyyssiiilllbbbbvvvcffrrrhhwwssskcccnwwwaddwv 3',
    'yyzzgggcctttcccuuurrrqgggcckk 5',
    'idddpppbbbummbdddpppccaaahhttxkkkyyy 4',
    'hhhhhhpplllkkkcctttskkkeeeebeeanaggdtmmnd 2',
    'qqqdddppzztttrrycyxxtttaxxggfwpppuuj 1',
    'bgggaaahhggfffddqjjjduuvvvpppooosmmmpp 1',
    'yysuummxiinttnxxxyy 2',
    'vvvvvvssakkkhhterrzzudaaaooowwxxswwp 5',
    'znnnsssuxfkhhhbggddttxxxkkkcccxxkkttthhmmm 1',
    'zttoooccrnuuiiillldddttrrhhhzzzpppddmqh 2',
    'eeennnwwwwuuoooooobpppoooggglffnvvvxbbpwwwxmmmmm 3',
    'kkgggahhhffftttvvvcccmmmzzzaaaxiibbcjjjjjjttt 1',
    'iiizzmttaabbbqqqlllvvvrrrccc 3',
    'hhsssfffudosppprrppwwyyygggxxxiiiaaazzz 3',
    'vvvccrrwwnnjzzzpppiipp 1',
    'kkaaattmmkkkcccimmssszzz 2',
    'szztttvvvxeekkkeewaaahhhtttdotttwujjjm 2',
    'uuvvvzddtoocclkkkffkkqfuuuddqmmeeeppppyy 5',
    'xxxzzaaaaaazzsnnhzuuulllnnonnlllxxbbbgguuubbccczuu 3',
    'kkkfffzzzvxlcgppjjqqgjjlluqqqcaguuu 2',
    'wttthhwwyyyppplppkkffdmmm 5',
    'ggiiiyfttkddwwzzoooggipppffrryaawwts 1',
    'gffwwzzzzzzbbrrrwwwiiizzzddllldwwbbbsszmii 3',
    'tthhjjjeeeppwwwhttgggb 1',
    'vvvyyyiiwlllcccoouuuoooknnrrarrrnyyywww 5',
    'ukkkvuuuiivvvlllubbffwwdgzzp 1',
    'nnxxxvvtjjjfjqrrezzziizzbx 2',
    'lllwwwwrrrgggzzzyyyrrmmttllklwwizz 5',
    'tttddmwrrrvvkkkyfffuuummmdddrrjf 4',
    'xccchxxwwffimmmmakyysnnniiinnnbb 4',
    'xxxuuuuubbrrrkxdvvlljjwwwpppvvvyyvthrpfffabbbnv 3',
    'xxxoommmgwwwqqppplqqqiiidduuuggjjjffflllfvvvfffvvvaazzz 5',
    'rrrfuuujjjlnlllzzkkcprrkkktthhaauaayyy 5',
    'zzzbbbpahhpiizjjuooo 5',
    'ollwxxxammtdorrraaaixxmqovvvkkmvvvjccyyttt 2',
    'iiimmcaarzzjjjggvyyyummmdxxxq 3',
    'lqqqlbbgggllppfcccqqqmmm 1',
    'scclfvvzzooouurnndddddssskkvuvvvvveekeeezssdd 1',
    'vcccepmmmlluuuiiidpppqnnnl 2',
    'iiaaaulllggyyyoohhttjjrxaallkkkolooollxxxrrccc 2',
    'nnjjjrsssooaaassskkkxxrriiihhhziiyqhbaaxxxaulllgl 3',
    'hujxxxxtzzpphgtttdssssstqyy 3',
    'sfffmmmoolyyeeciiiraaciswwtttznnnpoo 5',
    'qqfzbmmmmmrvvvuuuwwwwwwccchwwwggjjjxxxpbpqnnsllee 2',
    'cssspppiiidgggyyllmm 3',
    'uuyymrrppswwwwjjnnnihhhfffnnnutttccnnnfmmhhppyymmuu 2',
    'vvfffcclllpphmmmmeee 3',
    'nnnvvfffdddmmcccuuufwjjyyynnnsxkkkggnnnvvadd 3',
    'vzzzbbbaabblllkddomiiixxxjjjqjjj 3',
    'isttvooooojkkkaaafffiii 4',
    'bbzzzuukkllljjyyfvvvgggooorxxooyyxxqqglllkppggg 3',
    'aarrppbbbsxhhrriiccbbbsoozzzyyaaabbttteelll 3',
    'fuuufosxxxxvvuuuttss 1',
    'oogjjdddbkkkkkkjjjgjjgqqq 4',
    'zzzrrrwuutkkkcclllwyy 5',
    'gggqqqpfffmmeeennnrooohmxxxuuooqvvqqqpaaarr 4',
    'ruuhhhfffjjpgggyyycffxxxzmmgggppkkjjvvviqqqxxfff 1',
    'mtmmqqqdnnvvxxxvvtttqqquuunnn 2',
    'bbmmmllccwwnssvvbbkeegggjzzzqqqlmwy 3',
    'yyftttwwwjzzzoggkkkddztt 4',
    'jjjlpbbdddnnnttttuuusuhhhfkkgggllllnnbxkkk 2',
    'ggppljjjrriiioooqmmmjakkkfmrrgggmmm 1',
    'zzzkytccqzzttnhvvvwfmmmnwwwllmkkkdddtttooo 3',
    'llltttoomkeeeggmmqsyyy 1',
    'cchhhttppxxqqqllljtterraamdccczzk 4',
    'rrxxxkjjffhjjjkkkyyyiqqqqqyeeu 2',
    'xxbbbttmmapppyommuuuwwlllyyattkjvvoopiidddnn 3',
    'nnnbbxxoccoooaddllwwhn 1',
    'fbbbrrrollloilcccysdddelooobbb 4',
    'rrrnnnfffffffsqqyyyjjjsccczzzffvfffnggr 5',
    'mlltttjjfffqqqggjjnnnllluuutkkkmvvpdddggg 3',
    'vvvvvmttcoccrfffxxx 4',
    'kkpppennnjjqqqvxxqqqdfffrrqmmleeejjju 1',
    'nnnnngppddwwwkeeesppyyrrddbbbffrlq 5',
    'hhhaaarrkrhbbzwwwbxxx 3',
    'ttttwwnddhsefqqddtttffmmcccbbbyyyqqqkkuuzzzjjjff 4',
    'aafffxxttqtttkkkkkmmmonwrrraaaffdbnnn 3',
    'llppxxfkpppllzzzflccxxxzzznnuulllzzzbbyy 5',
    'wwwirwwaooolgnneeepppwwwggg 3',
    'kkkiisxxxlosddggkkuuunnnaaaddnnnvv 2',
    'mmjjrrxajjjczzcweeevvvddgggssseffffffaa 4',
    'oosssnnnlaaqgggfcckxm 2',
    'kkueevvfjlllbbbxxxhhhccsphhhttyylllcrrrscckkklzz 5',
    'llwjkkvvvmmmqkkrrresssgoooeeeuuuuugrrlxxxpppxxxzmmggg 1',
    'aaakdffppyyaayyabbyyiirxxxnnneebbbtttqqq 5',
    'vvddpyyjryywwwttffppplllff 5',
    'kkkmmbzppzzxxppewwwwwpppttyyij 3',
    'kkjjjbazhhwwnnwwvvaarroznnnvvzzddxxffxqqzzzqqqn 5',
    'aaajjjeetttvvppiggaaqqqllggpqqyyzzpuuumii 2',
    'ccczuuurrmiihyyssddooocccmjsyyxxzz 5',
    'sssziiiwgggmrriillloorooqllszzatttnnwwwxxx 5',
    'cciicccfttsjjjwwwrrrfffoeeezzoxxxwwykkssqqxx 4',
    'ffgdddzzxxccrrhheeehhhjjjlmmmlmmuggguummkk 1',
    'jjbmmskkffooovxxxetttveixrruuubbbffdvvvnnnuuuggg 1',
    'aaaytttdyyytttwmmmiiiuuuvvvhh 2',
    'jjjppppttgccrooofffiikojjjccvv 1',
    'jjjtooiilllcqqfcctnadddeeelffwmmrrrgggv 2',
    'pjjjztttqqqnncmnnjdddrrrgppzzzyeeevcwwyyyf 5',
    'vaaawbrrrqqqppaaeetttzzaaameteeezzzyyyoollxxvh 4',
    'yyaammmmmiiiwwjjjiwwnnynnnittthhheeerrrsskkk 2',
    'qybyyyeeqquuuoqqqsss 4',
    'yyfffkktggtjjqqqiffffggcc 4',
    'nnncccfggxmmbbbbmmvvv 3',
    'qsssxxggllhhhzjjskkmmpppgxxcccwwwwwuuuzzaaahhh 4',
    'dppssspppissuvvxxxrrrzzttdddhhhuiiimmm 2',
    'ddyyqqqpppdddbxxxnnjttkkkbbbggpplllyyyqqqbbbxxggjjjmmooo 3',
    'ffwwttlllwbnnbbbyyynnnmzzwwwbbbvgggmmpzzjj 1',
    'ccxxiiixmuuurrrrraaavvlleeeeeennnannooojjjyy 4',
    'ddddevxxhhhaaayyggxxwwwjjggedd 1',
    'kkyyrrwwwxxagggzoaoomfpppsaaaiffiiiwr 4',
    'fffyyoooccoopppiiimmmssskgggewmvvvvvvmjj 5',
    'lllapymlllaaavvvoooooohyyyzesqq 4',
    'muuttdddmmmoxdwwrrrzoobbrrraagaaatuuueeecm 2',
    'wwlxxlllsssrrsssrrkkknnnzzyyywkkkc 3',
    'jjiirrsyyyiwkkvvllzppgggoooooaviiiqqqrzzzrrrqqqzzz 4',
    'rrrqqfzmoooccfjjprrrnnyyyqq 2',
    'fskaaapvvvvvkrrruuddeeejj 3',
    'wwfffffyyyhhooozzzyywjvvqqdddppkkuujjjttthhhvooosnn 4',
    'dmmmaaccdeeeeooogffnnkkkbuunilkuuu 5',
    'ddjjjeeeitttssaaagggssspphoorrrpppbxtttuouuuaaabeeewww 3',
    'rrrssrccmmmcwwnnnbbbdjeeebbbcccnnnrrrhhhysnn 1',
    'hhhokkvvrxuuupplxxxnnkkgghzzeeeeeddtgggmmmqqffhoo 5',
    'rrrccbbbddccuuujjjllleehht 1',
    'wwnnnuuummmiiwwwmgiiimmmkkkiihhhccmddeelljjpttt 1',
    'uiqqqjddxfruullxhgggnnnkfvvhhccsssmmvvddd 3',
    'zzpmokkknneeezzwtttkkkeerrqq 5',
    'lcccqqqzlvvvdfilqqqggee 2',
    'jkkkraaabgggvvjjkwwvnkuullrrkkkkodddgttt 1',
    'bbbzzzccqqmmmrmmmaaaeefffjjjqquuuvzzzarrrwwatttbbnnb 3',
    'cchzzzlllljeetxxxyy 4',
    'eeeyymmmqfffppbbbstcccfuuusllim 4',
    'sssqqalljxxxffkkkkoodxxaeeuuubggeeemeeyyysmee 4',
    'uurrooomyyygqqqpppbgggvdddjjxxkkkiiikkozzuaa 5',
    'hhcuumnxxxbbwwyywww 3',
    'cccooolcccennecccjjjssskkhhdddxxmjjj 4',
    'ffayynnuuuzqttnaaaqqffqqaeekkkwooobroooyy 2',
    'hssselkkbiirryyymmmvlllmmbcccdddffullgxxooofff 2',
    'pppphhwwetffvvpppwwkkmmsspppiisshssswqqggeeerrrfff 4',
    'oommmssmmbgrrrnnnkwwwwwg 5',
    'hhhhhbbovvznnaaoozzeooolxxfffhhhfffffooofzuww 2',
    'yyyfffgggccbbbxxxlfffxxxwwwiisssvvvrrr 2',
    'tttjjjnnnyplllcssbbrrratttnnnkkkiinccceeiiidddtttiwwwffrrr 5',
    'llhhhvvcxpppzznaaawwwpppwwwfrrassnnnjjggpmjbjjj 3',
    'oooaaxxspwwwgmmrrrrrrgghhhooouuqmp 4',
    'eeennmjjjjjaaattooowaaviiwfffhhfffkkkrrrttwwwrrrlllb 5',
    'rrrkkrrraamggwwweebbqqqq 1',
    'ktttuuuvvddwwdmwwgggccjsssfvjjjiisssssspje 1',
    'iiuutttzyyyrraarrruuuvfvvvwwwnnnrrrgggn 3',
    'iiiiiwwlgggmxnnajxxwwwhhhjnnqqjfffbbbeeeiixccnn 4',
    'ttggkkkxxxyyyhhhcccyyiiooqqbddyyyzzzeeeggllpppw 4',
    'iigggqyyydgdbbpphhyykkllldnnnrddrrrvjjj 2',
    'ajjjkksuulfffgmkwwwxxxjjjnnnduuuqqqvvcc 4',
    'vvvdddemmqqpwwwyiiisskkkzzhhttt 3',
    'cmmrrhhhbbbkkkrnnkkppyyxxdyyy 2',
    'iisssbfffxxxzrrhrrrjrrgggaaa 4',
    'zzzswwccywwswfljyaaggdbxxxzttppplmxxxqsss 4',
    'kkdjjzyyuuvvmdvvjjsny 4',
    'bbaybvvvellldddgggjjjiiikkoonn 3',
    'rrrpiiscxxggxxxsssnnccchhrtttklllqqmbbbmmxggggggk 1',
    'iiivxxuuwwwnxkaaccmblldvveexxxxwwwzzzrrrmmvviiijjj 2',
    'grsssotfvvvvvyyqxxhhhylldxxaaab 5',
    'vmmmbbumllwddhhyykkkrvrrsssddbbbwwwdddsssyy 3',
    'yypppkkvvvbbllwwweennxxxjjccalllenbbbccvkkh 5',
    'ppmmbyyytttpppqtttffmmww 5',
    'ynnaapppsssqqvhggmlllyii 1',
    'ppgiiiffqqevvvemmmkqllliiimmmhhzyyqq 4',
    'xxzzzmmsssppsssvorrqqqdddgguuuwzsaavv 5',
    'spppggddpptqqgyyysbbbhhhgggddddyyeezzaaaim 2',
    'aaaiiiyyoubqqmmmyiaftczyr 1',
    'qqqlllkkkooolllpphbbbeeoonnnssseeuuuu 2',
    'tttiieeyyytaajxxeeffzzzuuurnnndddtttggzzzd 5',
    'aaavvpfmrryyymmmzzddgggqqmmmeebbbbzvvvjspppkkkuuu 3',
    'cccwuuubbbuuoaaeeewxxezeeerrcpzzzjj 3',
    'ggxlixxiizzxxlyueeettt 1',
    'kuuwwwnnnfffhhuukkkgggqqq 1',
    'ggaaavvqhpppgloaaaaaaapplxxdddgg 3',
    'eksssuuuggbbmmmvvvrrriiddtttkkkrrlllrrpppqqquuummmbbihhdddmmm 1',
    'ffrrrffabaaabtbbbdxxxllk 3',
    'ooimmmpkkxxxkiiigggf 3',
    'vqllgrmmhcffpp 1',
    'ppmssrrrccxwwdddhhhnnupxxdgg 2',
    'eeennrrooopppeeemggguuonnnoowwwiii 2',
    'zzzlcchkssmmoossstttlzzzhhh 3',
    'yrrbbuuutkkkbeetyyywwwttxxrmmmddqqppsssb 5',
    'fffiiipppdddaallbbbqqqyyygggughhhggbuoofffhjjtttvvvpccc 3',
    'ayxdddjjjhhvvnnnqqqnxxxppyyynaauuuccvviifffuuuakkyyy 2',
    'ccqqxxxxuuunnlllrzzzuuuqqjpiiittvvv 1',
    'xxxlllfdbttddsssvvvzzhhnd 4',
    'bbggjjjuudwiiqqttthhhkkddduuqqquuttpppgkkkgnvvvmmmbbb 3',
    'uuyyyqqccyyknnnlllueeooobskkoooccbbqqffffaaags 1',
    'ubbbwwmqqjjsssccqqnn 5',
    'sssheeemmmiiieeexxmmmgnnwwwhkktttegggy 5',
    'ytggglllbbvvzzjjvvvddduaaappmdddwdqqq 4',
    'mmmnkkddggghmmmttevrrmmzzz 3',
    'bbbvvhhffooocasbbxxnvvvc 2',
    'bbpppggeejtyydddpppjqqqzzmmmmmmqqff 1',
    'rcccdaaavvvtffqqqmmmuuiccwwii 4',
    'pprrccctjjjcczzzleeewi 1',
    'gsmmdyyymmnffpmmmttvvveeeiihh 1',
    'qqqbfffiiofffiikkkyyfxt 1',
    'qqwwwxxwmyybbbklvvvnnzmnnngrrrazpppggee 1',
    'aaarssskzslllgnnnllyylmmqyyuuuhhggg 5',
    'uupppcnnnhhhllsshhttteehuuuooozkssssssuuwqqqwwjjr 4',
    'ktaaaoohsssnvvbbxxnnnbbbit 4',
    'hhttlllcccdddyyyqqvjjjgbbrrdqqmmmmmhddxrxxxee 5',
    'aaauuryyoowttnnyyyaaz 5',
    'xxxrrrzwwnndrrrzzwwtooolllak 1',
    'rrllvvjjyjjjtttwwcqqhhjwzzzmzzttmlieeerrrt 1',
    'qqqnnnzzoppsiiiuussgggsrrrjnnnyyyddpprrrddd 4',
    'mmmbqooohhhuukgglllaaaiiimc 2',
    'akgglllllqqssnnndduuvv 1',
    'sssrlsskfffrssnkkkiiiixxxffqqbbbyypppfawhhhw 4',
    'nnnccmmrrbuuutttvvaafppxxxzyuyyysrrrappggnufff 1',
    'nnotthhhqqbbhhvvxtwww 3',
    'peeaajjjsssgkkkddffpppnnnlg 3',
    'rbrekkktttbbblablllzkkscuumddzzcssskktttffb 5',
    'peeewwyyyyvvsxssoqffttolllqqqmmmoc 1',
    'cccfffukkkceeldddzzzmmjjjzzzkgjiisdd 5',
    'hhffgxssuzztttfffttilllzzaaaeeejjjwwwehbbbbtw 3',
    'yyyggbbfffuuuyybbbllxxxetttuuucyye 4',
    'uuupppssdooknnnccrrffiiiiihiieeeppaabbbkkkwwccc 5',
    'sssfxgggyyhccxyyeexffddkkkrrrfdddkoomiicvvv 5',
    'vvcccunwwwrffgggvvjjjujjiiiweeennuuurddlllzzyyiijjj 4',
    'eeeegggpppeeejjaaaoobbbwwwwmmmvoooyyymmmyybjjj 5',
    'bbbiiyyemmvvqqcccmfffqrrfmxxxlmmbbfllaaayyxxxmkk 2',
    'kkktttauuvvssppwdcjjjcccnnnwwwiiixx 5',
    'yiiifffddmmpnrhhhhhhnmmmmmwwaamzz 4',
    'nppmqyyyuuvyytttbbkiggtrrffwwwzzrrrhhhqqddijj 3',
    'cccaayuppvvvyyyduuuqqqlcceeezuukkkjpiivkk 3',
    'iigggqzxtbbbddqqsssxoocc 3',
    'ooonnoooeejjjccrkhnnnmxdddsssslc 2',
    'kkccxxxbuuxxwtttquuiiiv 2',
    'rrqleeezsssssstttcacddduuuczzzhtttummss 3',
    'quuupbwxvvvjjpppqqqddrjllqqyyywwwiiilleekkc 2',
    'ommmxxdddqkkvvvdlkkkz 3',
    'vvbbbyyuiicccbbbcsfrrj 3',
    'ssppptbbvvvssqqqdddkkkqqooolllccckkkkkkrrnnn 5',
    'eyynnnpmmpphhhxxxeeezzjjjqqxxxxxhhgglllcfeexwweeqoo 4',
    'ooohhbbbbbxxehoxxxavvvtkkkzzzrrryppeeewnifff 1',
    'lloobbbyzzffzzzdddpppeeewwwppttcczzzaaqq 3',
    'xiiiiikkxxxoobbiilqqvvvkkyytttsmkkkeehkkkooo 2',
    'aaaooiiinnngggcccxxbaaaaaahhlrbeemmmllccffg 4',
    'qpppuujjiiinvvxapp 2',
    'illbbsssyymmmeeiiyywldddpvv 4',
    'tttqqaagmmkkbvvbboooyyyuuxzkkkfffrnnnqqnff 2',
    'hhhbbbggiiwtttooxoddmmxxxlllsqlllsxxxttzzjnoinn 2',
    'fdddhkzbbbmmmkkxxxeeebbfllii 3',
    'mmuuuzzttwwwtqqhissrrr 4',
    'mqqlaaayyyywwsssgxxx 2',
    'jjnnncxddqqqurrbciibxtttdlll 5',
    'qoaakkjfffsssnnncbbboov 4',
    'ooowwwbcciiwwmmoodddiiiyywiijjiidouqqqwjrrrbbgg 5',
    'dddwwwxxxiihffeeewweeexuxxxffr 5',
    'gaaarrrnxxxrywwwnaa 1',
]
test_out = [
    '14',
    '0',
    '9',
    '0',
    '10',
    '49',
    '0',
    '14',
    '27',
    '20',
    '53',
    '8',
    '0',
    '48',
    '23',
    '15',
    '29',
    '6',
    '0',
    '6',
    '16',
    '4',
    '4',
    '22',
    '9',
    '6',
    '27',
    '16',
    '0',
    '37',
    '13',
    '4',
    '5',
    '9',
    '8',
    '15',
    '3',
    '0',
    '0',
    '3',
    '0',
    '15',
    '21',
    '12',
    '5',
    '12',
    '4',
    '0',
    '15',
    '4',
    '0',
    '31',
    '28',
    '6',
    '0',
    '22',
    '21',
    '18',
    '0',
    '7',
    '0',
    '0',
    '17',
    '0',
    '0',
    '8',
    '0',
    '13',
    '0',
    '0',
    '0',
    '0',
    '6',
    '22',
    '0',
    '56',
    '0',
    '18',
    '6',
    '0',
    '7',
    '9',
    '18',
    '13',
    '49',
    '10',
    '19',
    '0',
    '38',
    '16',
    '14',
    '12',
    '6',
    '4',
    '0',
    '0',
    '0',
    '33',
    '0',
    '46',
    '0',
    '5',
    '34',
    '4',
    '15',
    '9',
    '15',
    '6',
    '0',
    '4',
    '0',
    '0',
    '22',
    '0',
    '0',
    '0',
    '49',
    '0',
    '27',
    '10',
    '5',
    '6',
    '0',
    '5',
    '4',
    '0',
    '0',
    '17',
    '23',
    '0',
    '6',
    '0',
    '30',
    '25',
    '16',
    '0',
    '10',
    '0',
    '5',
    '39',
    '37',
    '30',
    '26',
    '20',
    '7',
    '6',
    '50',
    '0',
    '14',
    '13',
    '28',
    '12',
    '32',
    '24',
    '3',
    '49',
    '0',
    '42',
    '0',
    '0',
    '4',
    '12',
    '34',
    '9',
    '0',
    '4',
    '29',
    '6',
    '16',
    '6',
    '6',
    '6',
    '35',
    '44',
    '54',
    '9',
    '15',
    '46',
    '25',
    '0',
    '8',
    '49',
    '50',
    '0',
    '22',
    '28',
    '0',
    '6',
    '16',
    '14',
    '9',
    '0',
    '15',
    '18',
    '6',
    '6',
    '5',
    '0',
    '29',
    '41',
    '3',
    '4',
    '0',
    '0',
    '0',
    '31',
    '7',
    '0',
    '27',
    '10',
    '9',
    '0',
    '0',
    '48',
    '0',
    '0',
    '0',
    '0',
    '4',
    '29',
    '0',
    '0',
    '3',
    '0',
    '24',
    '43',
    '0',
    '8',
    '10',
    '18',
    '39',
    '4',
    '3',
    '5',
    '6',
    '5',
    '6',
    '5',
    '6',
    '8',
    '10',
    '13',
    '8',
    '9',
    '25',
    '0',
    '6',
    '29',
    '6',
    '47',
    '17',
    '14',
    '0',
    '12',
    '6',
    '31',
    '22',
    '4',
    '6',
    '29',
    '0',
    '5',
    '0',
    '5',
    '17',
    '11',
    '6',
    '12',
    '5',
    '20',
    '5',
    '10',
    '0',
    '6',
    '19',
    '6',
    '3',
    '0',
    '0',
    '0',
    '3',
    '0',
    '0',
    '0',
    '51',
    '5',
    '8',
    '0',
    '0',
    '7',
    '16',
    '38',
    '0',
    '0',
    '5',
    '10',
    '0',
    '34',
    '0',
    '5',
    '0',
    '17',
    '9',
    '16',
    '6',
    '24',
    '0',
    '6',
    '32',
    '12',
    '42',
    '16',
    '7',
    '0',
    '0',
    '14',
    '0',
    '16',
    '22',
    '5',
    '22',
    '5',
    '0',
    '13',
    '0',
    '6',
    '5',
    '0',
    '0',
    '0',
    '42',
    '12',
    '13',
    '22',
    '7',
    '41',
    '11',
    '7',
    '9',
    '25',
    '0',
    '5',
    '0',
    '0',
    '25',
    '12',
    '0',
    '0',
    '0',
    '48',
    '8',
    '7',
    '6',
    '36',
    '32',
    '45',
    '10',
    '6',
    '6',
    '7',
    '9',
    '0',
    '0',
    '41',
    '36',
    '19',
    '4',
    '18',
    '0',
    '0',
    '7',
    '0',
    '5',
    '39',
    '4',
    '0',
    '0',
    '17',
    '11',
    '19',
    '50',
    '21',
    '16',
    '0',
    '19',
    '0',
    '12',
    '21',
    '0',
    '18',
    '48',
    '16',
    '3',
    '0',
    '9',
    '3',
    '15',
    '0',
    '16',
    '41',
    '29',
    '9',
    '8',
    '49',
    '0',
    '17',
    '6',
    '0',
    '14',
    '4',
    '11',
    '44',
    '0',
    '0',
    '6',
    '0',
    '6',
    '0',
    '9',
    '40',
    '0',
    '15',
    '0',
    '13',
    '8',
    '12',
    '0',
    '12',
    '10',
    '6',
    '45',
    '5',
    '4',
    '46',
    '5',
    '12',
    '0',
    '17',
    '16',
    '36',
    '16',
    '0',
    '37',
    '15',
    '11',
    '0',
    '15',
    '34',
    '0',
    '46',
    '12',
    '0',
    '0',
    '0',
    '21',
    '0',
    '32',
    '52',
    '27',
    '0',
    '28',
    '15',
    '0',
    '0',
    '6',
    '12',
    '0',
    '17',
    '0',
    '3',
    '6',
    '3',
    '0',
    '0',
    '14',
    '0',
    '6',
    '0',
    '39',
    '9',
    '3',
    '0',
    '32',
    '22',
    '0',
    '5',
    '24',
    '4',
    '39',
    '6',
    '0',
    '0',
    '16',
    '36',
    '12',
    '8',
    '46',
    '6',
    '11',
    '22',
    '5',
    '16',
    '6',
    '37',
    '20',
    '29',
    '0',
    '20',
    '0',
    '44',
    '10',
    '6',
    '9',
    '11',
    '0',
    '17',
    '20',
    '3',
    '9',
    '25',
    '8',
    '41',
    '33',
    '47',
    '23',
    '0',
    '0',
    '6',
    '15',
    '31',
    '12',
    '8',
    '19',
    '0',
    '0',
    '25',
    '48',
    '14',
    '3',
    '17',
    '22',
    '0',
    '0',
    '9',
    '0',
    '0',
    '0',
    '0',
    '27',
    '10',
    '3',
    '44',
    '5',
    '13',
    '9',
    '4',
    '0',
    '9',
    '5',
    '0',
    '47',
    '16',
    '6',
    '5',
    '20',
    '5',
    '0',
    '10',
    '4',
    '0',
    '0',
    '5',
    '0',
    '34',
    '16',
    '0',
    '5',
    '0',
    '0',
    '0',
    '15',
    '0',
    '0',
    '51',
    '11',
    '47',
    '3',
    '0',
    '8',
    '0',
    '42',
    '20',
    '5',
    '0',
    '15',
    '3',
    '37',
    '0',
    '15',
    '24',
    '18',
    '25',
    '0',
    '0',
    '0',
    '14',
    '18',
    '5',
    '6',
    '6',
    '0',
    '0',
    '28',
    '5',
    '7',
    '26',
    '8',
    '6',
    '3',
    '6',
    '0',
    '0',
    '17',
    '26',
    '6',
    '0',
    '5',
    '14',
    '12',
    '6',
    '0',
    '6',
    '6',
    '36',
    '14',
    '6',
    '24',
    '0',
    '0',
    '6',
    '11',
    '35',
    '8',
    '0',
    '18',
    '0',
    '8',
    '3',
    '11',
    '0',
    '3',
    '8',
    '6',
    '29',
    '29',
    '9',
    '0',
    '43',
    '32',
    '31',
    '6',
    '9',
    '0',
    '13',
    '6',
    '0',
    '19',
    '5',
    '0',
    '18',
    '21',
    '37',
    '0',
    '6',
    '9',
    '37',
    '0',
    '6',
    '0',
    '26',
    '0',
    '6',
    '8',
    '0',
    '19',
    '0',
    '0',
    '42',
    '6',
    '0',
    '0',
    '0',
    '21',
    '13',
    '0',
    '38',
    '9',
    '0',
    '48',
    '33',
    '9',
    '8',
    '6',
    '0',
    '0',
    '4',
    '0',
    '5',
    '10',
    '0',
    '0',
    '0',
    '12',
    '32',
    '47',
    '0',
    '12',
    '0',
    '0',
    '36',
    '0',
    '14',
    '17',
    '15',
    '12',
    '0',
    '0',
    '0',
    '0',
    '15',
    '11',
    '0',
    '34',
    '16',
    '9',
    '0',
    '3',
    '19',
    '0',
    '9',
    '41',
    '16',
    '4',
    '6',
    '3',
    '0',
    '0',
    '19',
    '36',
    '38',
    '16',
    '6',
    '42',
    '26',
    '10',
    '45',
    '18',
    '18',
    '22',
    '15',
    '9',
    '0',
    '13',
    '9',
    '0',
    '36',
    '33',
    '22',
    '0',
    '28',
    '7',
    '0',
    '0',
    '4',
    '9',
    '0',
    '0',
    '0',
    '7',
    '3',
    '24',
    '45',
    '11',
    '40',
    '9',
    '5',
    '0',
    '15',
    '9',
    '31',
    '7',
    '6',
    '9',
    '5',
    '9',
    '3',
    '20',
    '6',
    '0',
    '0',
    '48',
    '21',
    '6',
    '0',
    '15',
    '35',
    '12',
    '22',
    '0',
    '9',
    '3',
    '22',
    '0',
    '7',
    '6',
    '5',
    '37',
    '5',
    '6',
    '4',
    '11',
    '0',
    '12',
    '22',
    '6',
    '8',
    '0',
    '53',
    '0',
    '0',
    '8',
    '0',
    '22',
    '0',
    '0',
    '0',
    '42',
    '48',
    '14',
    '30',
    '8',
    '0',
    '0',
    '44',
    '0',
    '4',
    '11',
    '5',
    '38',
    '6',
    '42',
    '6',
    '30',
    '0',
    '0',
    '6',
    '11',
    '19',
    '16',
    '10',
    '5',
    '5',
    '0',
    '14',
    '44',
    '5',
    '26',
    '47',
    '6',
    '0',
    '7',
    '40',
    '6',
    '4',
    '0',
    '4',
    '0',
    '3',
    '0',
    '15',
    '10',
    '4',
    '5',
    '19',
    '20',
    '0',
    '12',
    '6',
    '5',
    '24',
    '42',
    '16',
    '5',
    '0',
    '24',
    '0',
    '6',
    '24',
    '0',
    '0',
    '0',
    '15',
    '49',
    '27',
    '5',
    '3',
    '0',
    '0',
    '24',
    '0',
    '0',
    '22',
    '25',
    '19',
    '0',
    '9',
    '8',
    '22',
    '25',
    '7',
    '61',
    '7',
    '12',
    '14',
    '10',
    '17',
    '6',
    '0',
    '12',
    '52',
    '35',
    '0',
    '9',
    '46',
    '0',
    '0',
    '0',
    '3',
    '12',
    '35',
    '0',
    '22',
    '29',
    '23',
    '39',
    '0',
    '6',
    '0',
    '5',
    '0',
    '28',
    '42',
    '0',
    '11',
    '22',
    '4',
    '46',
    '3',
    '6',
    '0',
    '34',
    '0',
    '8',
    '0',
    '5',
    '0',
    '0',
    '0',
    '40',
    '0',
    '6',
    '6',
    '6',
    '3',
    '15',
    '7',
    '3',
    '19',
    '3',
    '7',
    '6',
    '5',
    '44',
    '17',
    '17',
    '6',
    '10',
    '0',
    '17',
    '17',
    '6',
    '0',
    '12',
    '0',
    '0',
    '0',
    '0',
    '19',
]