test_inp = [
    'nhegIzItPYF',
    'sGUgDipZEqefri',
    'acesxurAKcaNSUmatJ',
    'wzOcVEKZeh',
    'mylnYshotvAHIrUC',
    'kVAKKi',
    'YbWuHQajtIwuQ',
    'DqOsNAfIx',
    'khut',
    'dSOr',
    'NNenTOm',
    'wMaGibwURLAK',
    'WyzJ',
    'eDW',
    'IGiHp',
    'hOKXybXUMMOM',
    'XFoPEDTir',
    'rASAJ',
    'zsIzepZYtxEmveh',
    'GVATcyCmOrYv',
    'NQaxluJ',
    'JWonqUXCurVIcAmkAG',
    'KEVweXrENwAKugODKeDPE',
    'geGUXuRAmKIFokLYh',
    'FJY',
    'oMZYwyXpyfCuzonITvuxC',
    'xNoSwUQWoV',
    'sbexNilzeWekVydoS',
    'aSokXAkNojnIGZoCheDT',
    'QaljYsL',
    'MagnyXDIfP',
    'Jb',
    'yPOJ',
    'izTirlaCcU',
    'DQamxOXnyMmAxkygSAf',
    'NIkgACKELQyLp',
    'koXunzagl',
    'DsAganjYRZitgimgI',
    'SFoGgIDN',
    'xIwdubKEQdascAZB',
    'PUPUMHYKtI',
    'MwYMFupiC',
    'rbucdy',
    'BEwRaGBYmTYSBal',
    'sELEMLyH',
    'PteLtuCVuwiqTiW',
    'qleLEB',
    'yGy',
    'dIsObyMduDMEcJUZjo',
    'ff',
    'xzennIwQivRYpKez',
    'NleN',
    'VMyZV',
    'RsIGjOqeQqojqo',
    'jSoqeZtU',
    'QmEpQ',
    'HZa',
    'Yz',
    'rlaWaLsiCHAX',
    'Zi',
    'nsECtEqme',
    'NkOVUFBiqaZUBNOcAHjuF',
    'scUmGEFapuRxUn',
    'LElEZSOWumZuhobJoWw',
    'fFUDTYPFIKMOBmE',
    'DTA',
    'nFuZFetkUBVUR',
    'kfyxPUbEp',
    'eBiKFY',
    'HCozRuT',
    'gboNrakq',
    'koxvYwwAbOcQa',
    'lpALMYsYczAgLirm',
    'sipWAXLUmkIxkad',
    'flIXCicWUg',
    'OLpUqvOTIlFiphIv',
    'mRafgE',
    'yxwYqraGpYj',
    'aGXEgfeZJA',
    'JcYGcomuMGOrTaQper',
    'MzYQXoFKevKODKy',
    'RYz',
    'xNeFPUNKeWdAvKePpI',
    'rvIJMULNaVlUxg',
    'ritRUPIvjoqHYcKYWi',
    'pRemHOpyNVazgY',
    'Usmece',
    'gRI',
    'PMEhsUXotoddehXi',
    'YvMEfbafFezPoMcugRi',
    'jYCNeVpaqKAzGi',
    'COTbyJxehxEbutPiV',
    'JePWAhjUlQeWK',
    'bCecKika',
    'PatxoFe',
    'VbirFiqEWLiqbylPeF',
    'RXAKZoBfIb',
    'sAHORWYzJeczocgUvVA',
    'LSyrzIk',
    'ZYgLoPfIXEXObSOB',
    'NkIbqoxgeqpArTO',
    'GqAMEMriQPOJHiTm',
    'RRiWZoVFoREcT',
    'iKTalL',
    'vJUH',
    'wpanOsyqzyqwaguWhAV',
    'WtuzsEnVI',
    'towR',
    'RBUFNEkLeVZUPSInkILDO',
    'GciqmodfIcRabEB',
    'IRBunXAv',
    'HTaNDEGVajPAcyXnubP',
    'vOzFOfXoC',
    'OXPAHfYkGOmExN',
    'wzewYhZaKcu',
    'avAWmy',
    'xxUkFySQYMrUmpEk',
    'XqU',
    'WUzqUmqU',
    'fT',
    'OFUpAwNANiDN',
    'AHHaVZ',
    'LwUrTubyvT',
    'npiqQaXSoKnaXcEVZudX',
    'XsedXANRYlPowLy',
    'QFIqQukHUhRYwiwJyjE',
    'HTac',
    'FDuDpOZ',
    'oQOqcUkYfxiBRuGegu',
    'RpYFnaMXufvIba',
    'fOrXyFqItolAWsEM',
    'LxeBeDToqbIC',
    'qQOWavTAjuQRyXYwgO',
    'QPOc',
    'RIcutcozLomyxmaju',
    'MxoZX',
    'YtgAqqufSeGkO',
    'RDOWuPehteXPYfaMq',
    'WkIzwOXFObAPmUbqAfl',
    'UJdENGumSUlKO',
    'lCowSIkMyjrOtqU',
    'rQIsJemnAQsIb',
    'NawiLzOKzezf',
    'aLSUTOCluQDeWNuHInk',
    'czUmqETZUZMOvG',
    'Gcy',
    'HsYLpELz',
    'vcA',
    'HyF',
    'OGpeVUkReGWIKRAd',
    'zuXfomCANEBQy',
    'HSiCMiHUZWaMrAkROtGuP',
    'LMejzyR',
    'RfugfYrcORnaxC',
    'jOjtEmibD',
    'yheZPevIvDo',
    'lBiBMyPx',
    'pweNIKnyJCoNteGMASBYz',
    'XJUdvitZYBafl',
    'BXuKWOZmoZkyHC',
    'IwtAVEJSejnALyzpuC',
    'UxgyFAZzuW',
    'lqumBocNutN',
    'pHI',
    'IZLeQCuPiZOtUgza',
    'QocQAh',
    'edINVYLjImlOjybPUFXY',
    'pLEhNuvZuWoMWiWAX',
    'Jvu',
    'xewtOfluPJyHty',
    'tsoMIkHUKdi',
    'clYXERMY',
    'WIZPAxMARfIlIZFeC',
    'epFaBbItYp',
    'VTYFbyzD',
    'WACxydlEpoNyNOkLeC',
    'jGiFNOHirwYhr',
    'ZKOFMy',
    'AXIRuQT',
    'KiMyPXUgpi',
    'YghUsAT',
    'FEJvAVAjEsgIk',
    'PyjOSmeZrywubILusNovN',
    'uSCuTJyzoHEnJAGUkEWtO',
    'GBefvAcaPxAHbAHt',
    'hyXcEJAKpelqyT',
    'Ejg',
    'xMenmYLLirQ',
    'MJoTvYGzufQAmZeN',
    'RCytHUPoFUHdulvEgpE',
    'WxaNHyFVi',
    'mMAfyPcugJiCJy',
    'xzOqqokOqjepbyzdoF',
    'KF',
    'XdUgzePRePgI',
    'JJEmhU',
    'ifobBev',
    'Zw',
    'BsYHGIDAXHEKYsYdT',
    'OglOMbyQZOClybB',
    'BKuxc',
    'wSacu',
    'ofASylENEtCuG',
    'JLakkyvC',
    'NFan',
    'xsoDiJViXMAgQE',
    'XJukjYqDiSLukHi',
    'TivnyhkoFs',
    'hGizs',
    'MGefjUTkygjumhoQa',
    'WeKjicpuvNUJkec',
    'fZOcbIRhYlvAvC',
    'MwOMhOfpYWIMsYlDel',
    'gpuHZI',
    'WwuwquWIDdAnpuvZEmbA',
    'hGIgl',
    'ImE',
    'OwS',
    'VoxvAsCi',
    'xNISXomVoWY',
    'FlipvYgvezu',
    'Tuxq',
    'qTinkAJB',
    'lipKInXogniFpEg',
    'DqeBQeZicnUliLxAwyVZ',
    'EZvYpFENZyXjeFNinkYPq',
    'xtoVHotwagEnci',
    'EsnEZFIL',
    'IqDOdGaNELV',
    'YwByqtAMjeCydPAk',
    'IbFUsKAvGuQsE',
    'CXidhODtywHa',
    'wpabMudFOwZiLQocF',
    'KOXqULbUreFTex',
    'umRUmtelAbtYnru',
    'YcHUVnaK',
    'VwejLeBqYqzak',
    'JaWONMoHjISqA',
    'Ci',
    'YrFOppUX',
    'fxehwAvKYMCIrQonw',
    'IzHONBilDyvKAxxIsUwv',
    'kwObLawfo',
    'itnYxtUTmoverIHZyzJO',
    'cUKeq',
    'SkyduKFELkO',
    'XwIHbez',
    'OkC',
    'LV',
    'vRidWyzIlkYgjARAjFum',
    'IJgak',
    'zqOWJu',
    'qaWyFRIfxo',
    'otCOqCUJGOSYFuvRUrvO',
    'PTE',
    'GaNlUPsIjeQvYXBukVYm',
    'bQIvkyhQImZypFysPudI',
    'aBynGoQ',
    'VyDECVOhXUXcaKzItn',
    'PrAdWApLEQBYsfEHjAW',
    'AKY',
    'UbByPkoCsiqc',
    'zYGEFdoswILoTbIVtOp',
    'dVoZ',
    'mDuXuCudvAX',
    'xqUxnuTwErovoniJGaPI',
    'efhOdxYXReFGeqKajloht',
    'sKePcUdciS',
    'DranzIxrenBeWhEP',
    'yQUzHUffAXjoHqOMe',
    'MGIkriQgEXcOHSyKHudd',
    'zOFdupEG',
    'dintided',
    'ufhYJRIWdE',
    'BpeLfaHBeFbyqjoZjaFL',
    'iRwEZIxKeZpUWmOgHU',
    'KanhiBCoZji',
    'tPOGJEZyRTYcquL',
    'mLoJPaXxyVgOhNyxe',
    'jGYrjotrEHdAGHeKBUreZ',
    'EjT',
    'hySMeRobrYCApxat',
    'fEkdY',
    'wKA',
    'WxALYrBe',
    'IFxEjNovadg',
    'JriGeSTEsAWB',
    'TI',
    'JuJtuR',
    'MYjFeGWaxSiRtYK',
    'qcykDUNKuCO',
    'ohteGTUk',
    'hTEHdYLorRypdAnhEDDej',
    'ZneHsyBdi',
    'KkiJpEmLox',
    'NuQgYKc',
    'yvZil',
    'TOmxOmaginhi',
    'UprUwZySZYFOsExQi',
    'tNAvmonAWfaTrUCDoVJ',
    'lWYGb',
    'APHYrjYnIJWoBh',
    'fR',
    'uGwApMUSfiCnYkjylNYk',
    'DGYFzEcgunxiqPEHjA',
    'PJOKXedSUhXahjOzZy',
    'CTUVmaQRIjRafEG',
    'bGYQIDE',
    'QdOru',
    'ifiKWaZ',
    'wEjLOzDUSmoSnEG',
    'uFanIZ',
    'GfABnEBatKIG',
    'hpInfeVHiRorl',
    'vrEsQyqlo',
    'NjellykgilQOBaQv',
    'UltaBhoF',
    'GECIDwewEhAZMYzwuwz',
    'xjaTcylypGOT',
    'YBJeBPiLPASRAj',
    'NLiCAqZygo',
    'iveDUStEJpAKPeWXOZPaw',
    'yfwohpidIctUzW',
    'wDoDTOHv',
    'bUgCYBnO',
    'zCaSNIJJIqRilYbUfM',
    'JTINcOJvA',
    'JAfdoZuvIFpoqfeTGyPG',
    'UpxoL',
    'ahtiZAjOMRifRagrUwQyx',
    'nIgjoZgySizResTUkFAf',
    'fpafPiXVAxrYBXAFULIj',
    'jFyBZUMN',
    'GSAHdExBywZUQRot',
    'zjuJliBnYthapGUj',
    'olKOlTYLMeNOfcyx',
    'ylOBXixcInfIXqO',
    'KwOS',
    'MEdNemNuWrElDyjmEqm',
    'hyZMIslOpPIJUrYRYth',
    'NeNsAxGa',
    'ohZalEGVaQ',
    'ozWYByt',
    'rFIXxEWDerBuMBIvDiXJe',
    'Wc',
    'JNObgaHtAKdiCTASuJy',
    'FyknyHGOz',
    'KBOXIZbysNAbaNla',
    'NVOvhOsodVIjylbozHUH',
    'zmAconEca',
    'jeqgIQ',
    'jXukKYz',
    'uTceQOSPAc',
    'nlivHy',
    'KQiTSo',
    'vYQe',
    'Wk',
    'HluVWiSSuLEPcASIDm',
    'zAjaSvUWqUjyfxEGrU',
    'kNUg',
    'UFUjujUnlEWJErgegtUSb',
    'LQAXcoNho',
    'ybITvIPTowj',
    'il',
    'yPKyQfeh',
    'YwB',
    'nnoCRYkcEbgytC',
    'JotkOVjUPo',
    'lDyLCyB',
    'SmaLsApX',
    'cFyP',
    'CcIVjIpzaZinkOHymQOzi',
    'PTuMWigdasSiVimZIZS',
    'JAPzAqoSPyhukTuxge',
    'zIRGehZOLPUdzuJDI',
    'UDEGc',
    'IRDILFanBIBamaGlOB',
    'cEbdomOcXigoV',
    'NnYtQIgNOVIlYHpewBI',
    'nqarVeCVapOFfIJiXn',
    'OxkiBohiCs',
    'Pdyju',
    'tYgipvyhSyXikGakOZ',
    'ffaVoDE',
    'riN',
    'jFUttYfhEqVYs',
    'mOpDAfWipObfoRQAs',
    'cgUmCajSUrEnF',
    'SZopwUtmaRBEgPuh',
    'taWGaQHemsuDU',
    'xIMHahVazIzEX',
    'PeLreHlUbcIKzawyR',
    'ZjaBRyZDofkUPJyHgI',
    'fYNMU',
    'ZHUptICjEHKASMoLMi',
    'lHYnkazeqciLtuff',
    'SpyGfazEH',
    'NRIbSizXaqSeF',
    'qfiZQiGTezU',
    'PconConJ',
    'eJCyzceX',
    'UJbOjdiW',
    'DcyFRYtSIFmYjtYdGEMEj',
    'ylVAMqenmUJK',
    'kZYGsEhlEtEr',
    'PuxOxx',
    'oHbeBEnBeRSAjIzAr',
    'ytEc',
    'Tze',
    'zHE',
    'fVOTVupx',
    'XDuZ',
    'XPEC',
    'SWUXE',
    'Jl',
    'RsemCIbhOkDUXZE',
    'sODByHyQwYnx',
    'XkuNREbCYrtAXF',
    'CkutdUMhiTITCA',
    'kOMsaLraFHIlvIC',
    'xXit',
    'CBUgnezizXogSecCIK',
    'aBRUZKESK',
    'vXyx',
    'cEDeCGetHU',
    'gijZyDREzcuqU',
    'TxUgnifGaLUNDUVQ',
    'NSuxvAdqaCcEdInQaSUsX',
    'iChAHAXcIgriscyLeGys',
    'GdOz',
    'pDoswANmuRtAZmusG',
    'cvIZXIhTO',
    'IzMUJw',
    'EDPuvZAqFAQAFF',
    'TlUgJYvR',
    'FanJAdTYpMAgNolRuVW',
    'UzQaKK',
    'yfsaWzABhurl',
    'GguBHezs',
    'UlJYBxYrTuwwaSHirHOT',
    'STOrvIfinHIRnAk',
    'hmu',
    'ASVuZaHELKIsExPecRY',
    'NhAjuWY',
    'yZWIhDIFhYslEk',
    'SSEWFyMgiGxyCLaTloL',
    'pt',
    'pJEzmUdfUTCUzJ',
    'SfIJqiBpERNuTji',
    'GqOWYglycjytmevpId',
    'kguZS',
    'MzYkPucODRyCevRo',
    'JhAcUciWdI',
    'WqAMnoFgIM',
    'gJESiSvETJorgiJWADE',
    'Uq',
    'CcanCec',
    'Gaxpo',
    'GObNiqXAnwOGnUk',
    'FqUBN',
    'HpolJixGeSzONv',
    'lJUlQUngajKEvrUgFY',
    'TyqnEPZaXWehbiNVENHO',
    'nvyVzUGxejLYQWOmmaMH',
    'xzuQNUzdESdA',
    'RgozhOPOJVIfVI',
    'aqKobIJfAJEmWOqQejh',
    'dguFjarP',
    'oLXeKmirYJ',
    'yNQYfyxiBzEWuPPEmfegb',
    'ljoDkYxDujHiQ',
    'iQLIMFEveHoPp',
    'XYqXenivODpAszoHSoj',
    'XZIpsyrOPugyFA',
    'aQWUS',
    'fvar',
    'KeRB',
    'kRuzj',
    'OwSIQbY',
    'rqISkUQLIzPolDOHME',
    'tIXsiHva',
    'KwORHEvdabBIBK',
    'XPAdevwOfCEhdAwN',
    'BZIWcEPxOMBumZOCiXfu',
    'yRveC',
    'cHuhhIJqivKEbQABj',
    'ZCALREFQOTJa',
    'QwUsMykhYWQujRI',
    'wiXZyPrAcGoPugWo',
    'uKfUrZiLHAHOVGY',
    'oSBerXePWuBLetXafTA',
    'ShyL',
    'ukDessIz',
    'UTVEsFozCudNULKedSyq',
    'yLIkOjiWxufBEj',
    'UGWYCGom',
    'mYzlORYdJaMadMihoMg',
    'YMuMhuNcyk',
    'tuqHOGXYd',
    'kQEHxoXRyPQYcLiC',
    'Sm',
    'Qs',
    'eJfEloWwidFOtog',
    'hriJjyW',
    'PYC',
    'cLUccY',
    'qsIbmEjpIpGOR',
    'dPaPvuHsuhilodJi',
    'xutwYxvEHZeN',
    'OVaLCEtfEKuNNaF',
    'GlAvVuWJAz',
    'bmiRhEnfebRIteqaRaG',
    'wXYWwUMIhvUJZIC',
    'GaDteLcejmOKD',
    'nNOdgOzVOzVYzhoR',
    'TMyNmOcHUCramY',
    'VcylQ',
    'hwoMGaqMi',
    'MYSyBKiwZYxehHYmryL',
    'XmYCdegNil',
    'GYKEZYKqEmhAqzaJlyGj',
    'AFINpinZufxYLcu',
    'RmiTMEMPabKUxEjM',
    'CXo',
    'RQeQZ',
    'XZAgPuwxiCTazTuGmAgvA',
    'AXWuxKijCyvqaSgILDit',
    'zaZ',
    'sajApsOnOvL',
    'FpestavsoZCElSaQWuQnU',
    'PmIfqoLKECinvasmiw',
    'RUsKiwIVOkKefubM',
    'xVibeHBIrcOJirYhUhw',
    'Rhi',
    'MqImR',
    'fGyVSIqdUnRyg',
    'jMYXp',
    'qgAjhYzFes',
    'vxomtEBZenWa',
    'tGUqgOWu',
    'LbYfeXfywRABbORPug',
    'GFeZlUX',
    'ddiS',
    'arEpIDJyZRyvHUv',
    'okO',
    'UPhANajZYVjuZDy',
    'SWOCS',
    'RziBfuSnEHeHFubafqYt',
    'CtYN',
    'yJKaT',
    'xaKRAfuvTEpnaVQu',
    'NojLYGJYVvyzYXaHz',
    'uNdEB',
    'inytTyqQIxifn',
    'moVwofrikyNivAZmyK',
    'WoXakveTaGsIcwadr',
    'lneNidLiBxehgosgeb',
    'TytLyGDyH',
    'ThofkuGrOdfOFG',
    'VANqobZ',
    'gcaTBukNuzj',
    'ScUT',
    'ZDen',
    'zxacLepSYwBaj',
    'GuZIsvOzzin',
    'VTyssIVOtZyhIjAQuC',
    'JqixyNpiRQ',
    'jECN',
    'YnGusroFqAGBolBOv',
    'UmzIkNIpEtqaJODFAs',
    'LmUfKiPFewCOKMOz',
    'NQYZtodNYl',
    'QtIvx',
    'mhoMKoKcYlHums',
    'imHIbelk',
    'wYGZUzryvI',
    'LXikg',
    'CfYhjyXLOrzUsnUJ',
    'yMleQneRaXjAptyLH',
    'IlZOwcIMqefBIfZubk',
    'rFaLQiJxawqAhy',
    'GXEmZigSoTVUlKUhs',
    'RPivcOHlaHnu',
    'iWzatmesCE',
    'IrFOpcEDORb',
    'HhOHmAcaTnawgUkSY',
    'wGOHubgO',
    'sFIgqobTAvRYbHutz',
    'eGsAwrAQIkUHriZNYwNI',
    'HHIVgElQANUtVyhGIQbIr',
    'csybCUlaKmYLveCUn',
    'CAVcUKBUC',
    'sBefKesA',
    'aKQidx',
    'TpUhfeHIWbUVAq',
    'FRaxTavvofBOrAHVU',
    'hc',
    'bROBxuFYTUHSIrvylWUNO',
    'bApoCsYKzija',
    'KMOwteqVODquPgU',
    'CiJijMoPxYLcIJ',
    'INLonMYGecDirmaSzUFH',
    'ikry',
    'yLqEFRukk',
    'ppEDTOzzA',
    'tTEZrirRepjiWDO',
    'sqOTFuGqE',
    'GYVfaXmaLnInWOvVIV',
    'ukvopB',
    'NMUmFujFEdykj',
    'gIGCOrvoLbYTs',
    'lSowFYgRa',
    'fquWykoBHYmLUZR',
    'AvmocK',
    'jzawh',
    'wUTuFvEwdaLEHW',
    'FBeHto',
    'mnihMiKUjcOtap',
    'MreXpANsiQsERZYrl',
    'gamYXLiCJ',
    'CwItlECUNnA',
    'ANlIRGUCHyGUnHe',
    'sQUl',
    'ZZaBfiw',
    'RbiRkoq',
    'SmELDEjGyto',
    'ot',
    'kBoMRyWOBmUQ',
    'BkeMHaPG',
    'CVEFNabhinCiBD',
    'oJNeHWYnqIqrARpOMDIq',
    'nC',
    'hrYfWervo',
    'BhONyjOPHuTsoPpyXN',
    'MTyhpeD',
    'atJuFIxWoQJOtbom',
    'xWo',
    'QvaRvipVOBmESdUjTYPB',
    'hvYP',
    'WbakxOR',
    'uMTeTBYR',
    'jACUKemHUsREbQInSOl',
    'aRBotfYzFebMI',
    'QENm',
    'JTYM',
    'eHpaJLeQHurwUHEF',
    'kyFOTETUQrITDI',
    'EXm',
    'dXOlq',
    'RoFFIdSOsJazOdEz',
    'dregQExvyxBYZzACEcMYW',
    'WILokgufMIhKUFty',
    'IsaWFOMriDUMoZvArW',
    'rhelUR',
    'fNyHqabNYdxodgIw',
    'xkAHByFjAlGIXlyz',
    'rcyVgecmi',
    'yjZYCwEKqYc',
    'siVFIRzurKy',
    'Slyn',
    'DIZCaQxIsfunQYlSYxZ',
    'hTOkYZOHmEPIdfuPA',
    'PMuKAcLikRISBUrJUSb',
    'omcYBsOZKeLKYhqEw',
    'ATkilzYZJic',
    'GHuMxy',
    'rPAvoWLIBAMh',
    'wageGW',
    'upotCOSlecC',
    'DCokmoMROCKyjAnwiVr',
    'GpaRNapYj',
    'PAkWOGfIbywhavPOBBEgV',
    'WPoJTifijoDozz',
    'VJEBpy',
    'PtEmBYraBAfhaTPivUw',
    'GVEvhOnWAXSixaGDEnYW',
    'eg',
    'OFYrLezaHyRik',
    'NOxiNx',
    'pbEmK',
    'KAKjOJliLPYMJAtGU',
    'AJbItkepLOWjuZfYRme',
    'apIHnAXAfgIQRojk',
    'MRUnYnIVYtVOC',
    'QruPxOdBuMbE',
    'lZ',
    'qUv',
    'aTqA',
    'FJO',
    'GfUh',
    'Df',
    'PESEXvIHhAjVeM',
    'tFYwEvjEgrefzEWHihoS',
    'YCVyqAsRexjEXUrV',
    'XRYldYSnOfAxwalVo',
    'jNuwtoPweJHoFcuZjySZA',
    'wC',
    'bDAhSucvaBpApXarZ',
    'FUBvAWgUTIHRe',
    'KseMrEmcY',
    'FlyJofdACeKJA',
    'ucasOFHAhDeSTOV',
    'fsUs',
    'lxaKhuszAQXiLxEF',
    'spEd',
    'fRY',
    'RDalzYtrImUh',
    'JNYfRYqu',
    'mfIBPOfCuknIwgyhWOF',
    'pvYZuchEQrUh',
    'MYlNIRdYwfyP',
    'mfEVLeCQyg',
    'WOhmilhu',
    'unweljuvaG',
    'AQPeWJILuTmaWtagu',
    'Apwom',
    'USneXSIMqepRagWetB',
    'mnUDNuFsOwOQsASRiBVe',
    'nmUcYKmytlyfTEQPUz',
    'GXiJSEM',
    'CoFekyZzi',
    'agZydJyPeR',
    'VTo',
    'oJadhuHkYcdeLYXaTg',
    'riJpAJaKQamZEtuC',
    'BUSUkWOPICahLuvD',
    'rCYwrecWowENPipfEgsE',
    'LZuxJohUP',
    'ffIppICteKzABpeKWEdV',
    'RIrIhz',
    'tFeTwyzyRsOPinmISQE',
    'LxICyvzuFvElfysFa',
    'akgyF',
    'RFIpOftYmQuhCAStUw',
    'eRvEszoMLuWhesv',
    'egOgSYvC',
    'GYBEPSOkfEFMyp',
    'YqsiMxoMrejF',
    'JEmYHvAbVA',
    'TdYXMidfojJakpopd',
    'TcosOVxyzAnANGUmbupV',
    'PDUfkYHdELHiRJaZHUcZ',
    'Vnisnyj',
    'CcifZepPAMHetFOlw',
    'RsixzYLETYM',
    'jhIcVO',
    'fExCOrIfPukIV',
    'DDAhIkZypvafrI',
    'hXeTJAQgUzhEHofz',
    'gtowFeTYwB',
    'PE',
    'nWeZidhe',
    'PQ',
    'yJoVbUlHEb',
    'cGiRVEfmUj',
    'aJULrEwREGvEMrilIZzE',
    'ebytEJrABXiL',
    'XuflijUmG',
    'OdbUcbuXPeMZuhZYZQ',
    'GXeTu',
    'JtogpinibR',
    'RBYnisPi',
    'lDYQVoDdoVUhVEgO',
    'FnuTDaLVuNPELUX',
    'XeWjOcqUmrUfsOflit',
    'NWatxAVgaWmiDKyFxiSI',
    'qmYNcen',
    'tbARunWAdHonSaRCins',
    'XOcodpo',
    'enfidAQ',
    'NJy',
    'rrAksyJu',
    'yWkOraQfAcpAdlaffUVG',
    'GdAlcOFAtZewMOFp',
    'WBAwQIWXICigm',
    'tasleZEwso',
    'qGEDJEXo',
    'CqOnrYSpAcjYVfIbiColY',
    'LynZaHmaQInQuKjaxw',
    'DkovlENUfSYvJADuFbOvx',
    'EgSOXmewbozGATv',
    'wGiprogJePfagV',
    'xoBcYTJYxvak',
    'ndIwHo',
    'zli',
    'CsEGHUZhUCynVuzwikNow',
    'NaZZEHfuJadGAzuCs',
    'XwoTDyJ',
    'zOkeBUWvImCufDum',
    'fKEnvUNPYVvoHHY',
    'xxanesQA',
    'txysfOKz',
    'TDUGgambiLfolRaBvAjYl',
    'tCEBzO',
    'lGymlOJRu',
    'ZdutqOVbYjyNnaw',
    'mloBt',
    'lSAVJiZvUZNuQqE',
    'FwObOGwYcAf',
    'wGYVTehZAJPesNaQbiZM',
    'JBAdBIpfYjLEglAmA',
    'pHazRIJ',
    'ZJOspaFola',
    'fwOPZynWim',
    'uqREVJEBwyBbY',
    'FwOsQ',
    'fcegQYdZO',
    'mwUd',
    'xmUXhElW',
    'mHYbXarO',
    'sRufbuHwIwTuHdogf',
    'wSiDpUbBASWOq',
    'NS',
    'KxIBmoHHeGh',
    'HOCqeRiPfywBYXOdtIwpO',
    'tvUc',
    'wNybqAQOKd',
    'NbyccavNeDaxFI',
    'fFeDediQo',
    'uTJiMICsi',
    'yJZEfZErAmUbXItquSF',
    'SveQToZDOVtoTYpH',
    'yltiPxAkwo',
    'mfirbAWkigsujlUzWeb',
    'OBlYtwymWExrosnedsaNe',
    'iwxe',
    'nHiPbenbyXnolTiXPycm',
    'ZboMUViswU',
    'JohUZBOB',
    'ECNoMkYzAxMuT',
    'Co',
    'nyDlAQVOMOXhOTVuvS',
    'vE',
    'eWENFyqrORHakXa',
    'lgikoVvItrytxAK',
    'xWU',
    'cNEvWUwybRYStubo',
    'GZEmkywTaxk',
    'UcHeQnEspacso',
    'IkoSfEQPUnyqGE',
    'IvorOBcydhaGyXciB',
    'RZ',
    'VOmJEmKA',
    'sySqIctUwfA',
    'gUVoMHaDo',
    'DjiggIrCOPNUdYbyz',
    'rTYqSyzbOQj',
    'YfIvmUGnufjOxh',
    'cGYctinIvsA',
    'mzOtU',
    'nzo',
    'BYDOKIKmIPuDvYNoHDaw',
    'BfEPqicXAvPURHoMBAL',
    'OLatF',
    'aTmAhpEMuwLUJkEbP',
    'wQIxqyZre',
    'JqyzumLOtGavOSV',
    'VaXjyHzAfLoVuQjEKLAsM',
    'eLuzQYjaGdoMhInceHMa',
    'ftakr',
    'ARSahseJcAmVOLf',
    'AM',
    'kDawmOWehXiRKipJO',
    'UrweQOPsyRDiLRI',
    'mmOBvAgwIZq',
    'YXGoDkArIJemfuw',
    'kXeHbYRHYrmIXILBOzL',
    'VwAMwOgiPkUQHYVedPOs',
    'BiDjAp',
    'pzIloLDIbNAfX',
    'KoKg',
    'ASzURJiGiMnixcyQF',
    'vPIcQALUMxyd',
    'EVgURPuTVUZLyZ',
    'zNUhcIFTY',
    'EPciRQEBPeQRYBeDgersi',
    'hqUkUFmaXnUdZUMaPU',
    'twITaNynOzeDViSsy',
    'pXAWz',
    'jMe',
    'VpIWqoQzISO',
    'bFITQewYpifZifyw',
    'bvUDmOkGatgUrtiKSudd',
    'FcefCUNonhAdUXxIdY',
    'aNQyJVYniFYxLy',
    'vOhJaRbiHtujXaqxUDm',
    'hD',
    'GvIGEsmAc',
    'FEDqeZcovb',
    'vGEjSySEDeQuCjUdB',
    'RliWoFXEjyhfe',
    'iJj',
    'XWanoPyv',
    'NBevBezPOlgepZedypn',
    'LFEnf',
    'vcOktiqXen',
    'xuKyqwicuvmiGevKUraC',
    'wFAJNiPUtCUzgaJvo',
    'hXaCpEdKAs',
    'ACre',
    'MMOlmYZGAWUSBURLiJ',
    'fcezbiWgaKmyCP',
    'bBiq',
    'prO',
    'sHYFwuVvEsZ',
    'SGetxUdaWpY',
    'yFQolPUfXURfyb',
    'oMriGfyBsA',
    'obZ',
    'BwUXHEXO',
    'tVUrgEhduTK',
    'eqxOJkaFlARSOqmYkDyz',
    'lqAh',
    'dZyHoSeWzoVFILpAdREMq',
    'CjuLWI',
    'MqE',
    'oqr',
    'Fp',
    'PKY',
    'nFI',
    'NdoZJOGyxFyWLIzK',
    'PWicQawdUmv',
    'HgUd',
    'SfUHjYW',
    'zhUsaddUcwUg',
    'IrGopceWmESFAC',
    'CS',
    'JeltUVGEMdAGybAx',
    'oQTY',
    'Mx',
    'RXeviTWIntax',
    'ojqEfDIqexSEvg',
    'DGIwAHgASgEh',
    'smoHUjnYrWyKLYl',
    'qrEfIZdavVaLidqaX',
    'ESsAPQYVDOwhaVUddy',
    'igNIHkoMBacoVh',
    'gHuZWYmHeVbimITtiZaPb',
    'LfiQWUkAhTECe',
    'TnOLedMAFZ',
    'cJEjURpUWeDLIqfeRT',
    'khEkBIHSIwAv',
    'UkGiZoJlYcIM',
    'XWekZySgyZsyblE',
    'ZiGtIQG',
    'XqymZUz',
    'lX',
    'fmoLDUCZidsusElgE',
    'AmWeGetJara',
    'CHaMS',
    'dX',
    'OMvuHVuMwOJdyF',
    'zZAMo',
    'xIphyxWUBGikc',
    'wPosQuCXY',
    'NKICNapTeMJov',
    'VEWkeZWaHYqcYKdYMNUW',
    'JQatHOC',
    'gQeSn',
    'IDzemsOqYhPOnUqr',
    'SuZBEKGY',
    'NrOZsIgDagOrQEzMaX',
    'vXAqh',
    'KOMKogvIKpiwHERtOQELp',
    'msUQ',
    'XmiljejPiHkEFrelgALWI',
    'xLI',
    'PU',
    'TfYracAzsoTpOPJYSkavq',
    'IvFibtuFTExYvEJJeKF',
    'qbinuMviNJYQUME',
    'LFAdTobCa',
    'jtuhDejufKeKVe',
    'rRyRi',
    'NyWRuCLYRLadPywvuQg',
    'kcOwpaHj',
    'AJHEfbarrEfPinOsOk',
    'uMOxYkaBOkQEPyLXyPi',
    'FbekWUPiCyhTE',
    'OCMybvEWJIx',
    'zDuDSUVBUKpezGyhVYdM',
    'kUdfAPHEXeQorBoTvuxs',
    'LTYrDod',
    'AwwU',
    'QwOGFuDhIMPoKyle',
    'tyrweCR',
    'CUfq',
    'XrAQFipYZbEP',
    'FgUrZINItNOgje',
    'wcEhLIdhavki',
    'odQUw',
    'wfISYjCowZY',
    'iHzIwMEVTarU',
    'eWzeBiZluTOrWEGPU',
    'VwytVoWdoHxIwypm',
    'EcoQGE',
    'CHykko',
    'NkeSWyglI',
    'BkamdUZwaXbaZFYNJ',
    'WU',
    "pokemon",
    "pancake",
    "hotel",
    "Anna",
    "python",
    "discord",
    "challenge",
    "development",
    "and",
    "random",
    "chat",
    "pass",
    "sure",
    "am",
    "more",
    "thank",
    "very",
    "result",
    "we",
    "gonna",
    "pretty",
    "started",
    "shortening",
    "syllables",
    "there",
    "consecutive",
    "nothing",
    "according",
    "uses",
    "use",
    "advanced",
    "different",
    "into",
    "project",
    "writing",
    "testing",
    "something",
    "alerting",
    "favorite",
    "make",
    "syllable",
    "snEXpe",
]
test_out = [
    'nhe gI zIt PYF',
    'sGUg Dip ZE qef ri',
    'a ces xu rAK caN SU mat J',
    'wzOc VEK Zeh',
    'myl nYs hot vA HI rUC',
    'kVAK Ki',
    'Yb WuH Qaj tI wuQ',
    'DqOs NA fIx',
    'khut',
    'dSOr',
    'NNen TOm',
    'wMa Gib wUR LAK',
    'Wyz J',
    'eD W',
    'I GiH p',
    'hOK Xyb XUM MOM',
    'XFo PED Tir',
    'rA SAJ',
    'zsI zep ZYt xEm veh',
    'GVAT cyC mO rYv',
    'NQax luJ',
    'JWon qUX Cur VI cAm kAG',
    'KEV weX rEN wA Ku gOD KeDPE',
    'ge GU Xu RAm KI Fok LYh',
    'FJY',
    'oM ZY wyX pyf Cu zo nIT vux C',
    'xNoS wUQ WoV',
    'sbex Nil ze Wek Vy doS',
    'a Sok XAk Noj nIG ZoC heD T',
    'Qal jYs L',
    'Mag nyX DIf P',
    'Jb',
    'y POJ',
    'iz Tir laC cU',
    'DQam xOX nyM mAx kyg SAf',
    'NIk gAC KEL QyL p',
    'ko Xun zag l',
    'DsA gan jYR Zit gim gI',
    'SFoG gID N',
    'xIw dub KEQ das cAZ B',
    'PU PUM HYK tI',
    'MwYM Fu piC',
    'rbuc dy',
    'BEw RaG BYm TYS Bal',
    'sE LEM LyH',
    'PteL tuC Vu wiq TiW',
    'qle LEB',
    'y Gy',
    'dI sO byM duD MEc JUZ jo',
    'ff',
    'xzen nIw Qiv RYp Kez',
    'NleN',
    'VMyZ V',
    'RsIG jO qeQ qoj qo',
    'jSo qeZ tU',
    'QmEp Q',
    'HZa',
    'Yz',
    'rla WaL siC HAX',
    'Zi',
    'nsEC tEqme',
    'NkO VUF Bi qa ZUB NO cAH juF',
    'scUm GE Fa puR xUn',
    'LE lEZ SO Wum Zu hob JoW w',
    'fFUD TYP FIK MOBmE',
    'DTA',
    'nFuZ Fet kUB VUR',
    'kfyx PU bEp',
    'e BiK FY',
    'HCoz RuT',
    'gboN rak q',
    'kox vYw wA bOc Qa',
    'lpAL MY sYc zAg Lir m',
    'sip WAX LUm kIx kad',
    'flIX Cic WUg',
    'OL pUq vO TIl Fip hIv',
    'mRafgE',
    'yx wYq raG pYj',
    'aG XEg feZ JA',
    'JcYG co muM GOr TaQ per',
    'MzYQ XoF Kev KOD Ky',
    'RYz',
    'xNeF PUN KeW dAv KeP pI',
    'rvIJ MUL NaV lUx g',
    'rit RU PIv joq HYc KY Wi',
    'pRem HO pyN Vaz gY',
    'Us mece',
    'gRI',
    'PMEh sU Xo tod deh Xi',
    'Yv MEf baf Fez PoM cug Ri',
    'jYC NeV paq KAz Gi',
    'COT byJ xeh xE but PiV',
    'JeP WAh jUl QeW K',
    'bCec Ki ka',
    'Pat xoFe',
    'Vbir Fi qEW Liq byl PeF',
    'RXAK ZoB fIb',
    'sA HOR WYz Jec zoc gUv VA',
    'LSyr zIk',
    'ZYg LoP fI XE XOb SOB',
    'NkIb qox geq pAr TO',
    'GqA MEM riQ POJ HiT m',
    'RRiW ZoV Fo REc T',
    'iK Tal L',
    'vJUH',
    'wpa nO syq zyq wa guW hAV',
    'Wtuz sEn VI',
    'tow R',
    'RBUF NEk LeV ZUP SIn kIL DO',
    'Gciq mod fIc Ra bEB',
    'IR Bun XAv',
    'HTaN DEG Vaj PA cyX nub P',
    'vOz FOf XoC',
    'OX PAH fYk GO mEx N',
    'wze wYh ZaK cu',
    'a vAW my',
    'xxUk FyS QYM rUm pEk',
    'XqU',
    'WUz qUm qU',
    'fT',
    'O FU pAw NA NiD N',
    'AH HaV Z',
    'LwUr Tu byv T',
    'npiq QaX SoK naX cEV Zud X',
    'Xsed XAN RYl Pow Ly',
    'QFIq Quk HUh RY wiw JyjE',
    'HTac',
    'FDuD pOZ',
    'o QOq cU kYf xiB Ru Ge gu',
    'RpYF naM Xuf vI ba',
    'fOr XyF qI to lAW sEM',
    'Lxe BeD Toq bIC',
    'qQO Wav TA juQ Ry XYw gO',
    'QPOc',
    'RI cut coz Lo myx ma ju',
    'MxoZ X',
    'Yt gAq quf SeG kO',
    'RDO Wu Peh teX PY faM q',
    'WkIz wOX FO bAP mUb qAf l',
    'UJ dEN Gum SUl KO',
    'lCow SIk Myj rOt qU',
    'rQIs Jem nAQ sIb',
    'Na wiL zOK zez f',
    'aL SU TOC luQ DeW Nu HIn k',
    'czUm qET ZUZ MOv G',
    'Gcy',
    'HsYL pEL z',
    'vcA',
    'HyF',
    'OG pe VUk ReG WIK RAd',
    'zuX fom CA NEB Qy',
    'HSiC Mi HUZ WaM rAk ROt GuP',
    'LMej zyR',
    'Rfug fYr cOR nax C',
    'jOj tE mib D',
    'y heZ Pe vIv Do',
    'lBiB MyP x',
    'pwe NIK nyJ CoN teG MAS BYz',
    'XJUd vit ZY Baf l',
    'BXuK WOZ moZ kyH C',
    'Iw tA VEJ Sej nA Lyz puC',
    'Ux gy FAZ zuW',
    'lqum Boc Nut N',
    'pHI',
    'IZ LeQ Cu Pi ZO tUg za',
    'Qoc QAh',
    'e dIN VYL jIm lO jyb PUF XY',
    'pLEh Nuv Zu WoM Wi WAX',
    'Jvu',
    'xew tOf luP JyH ty',
    'tso MIk HUK di',
    'clY XER MY',
    'WIZ PAx MAR fI lIZ FeC',
    'ep FaB bI tYp',
    'VTYF byz D',
    'WAC xyd lE po Ny NOk LeC',
    'jGiF NO Hir wYh r',
    'ZKOF My',
    'A XI RuQ T',
    'Ki MyP XUg pi',
    'Yg hU sAT',
    'FEJ vA VA jEs gIk',
    'Py jOS meZ ry wu bI Lus Nov N',
    'uS CuT Jy zo HEn JA GU kEW tO',
    'GBef vA caP xAH bAH t',
    'hyX cE JAK pel qyT',
    'Ej g',
    'xMen mYL Lir Q',
    'MJoT vYG zuf QAm ZeN',
    'RCyt HU Po FUH dul vEgpE',
    'WxaN HyF Vi',
    'mMA fyP cug JiC Jy',
    'xzOq qo kOq jep byz doF',
    'KF',
    'XdUg zeP ReP gI',
    'JJEm hU',
    'i fob Bev',
    'Zw',
    'BsYH GI DAX HE KY sYd T',
    'Og lOM byQ ZOC lyb B',
    'BKux c',
    'wSa cu',
    'o fA Sy lE NEt CuG',
    'JLak kyv C',
    'NFan',
    'xso DiJ ViX MAgQE',
    'XJuk jYq DiS Luk Hi',
    'Tiv nyh koF s',
    'hGiz s',
    'MGef jUT kyg jum ho Qa',
    'WeK jic puv NUJ kec',
    'fZOc bIR hYl vAv C',
    'MwOM hOf pY WIM sYl Del',
    'gpuH ZI',
    'Wwuw qu WID dAn puv ZEm bA',
    'hGIg l',
    'ImE',
    'Ow S',
    'Vox vAs Ci',
    'xNIS Xom Vo WY',
    'Flip vYg ve zu',
    'Tux q',
    'qTin kAJ B',
    'lip KIn Xog niF pEg',
    'DqeB Qe Zic nU liL xA wyV Z',
    'EZ vYp FEN ZyX jeF Nin kYP q',
    'xtoV Hot wa gEn ci',
    'Es nEZ FIL',
    'Iq DOd Ga NEL V',
    'Yw Byq tAM je Cyd PAk',
    'Ib FUs KAv GuQsE',
    'CXid hOD tyw Ha',
    'wpab Mud FOw ZiL Qoc F',
    'KOX qUL bU reF Tex',
    'um RUm te lAb tYn ru',
    'Yc HUV naK',
    'Vwej LeB qYq zak',
    'Ja WON MoH jIS qA',
    'Ci',
    'Yr FOp pUX',
    'fxeh wAv KYM CIr Qon w',
    'Iz HON Bil Dyv KAx xI sUw v',
    'kwOb Law fo',
    'it nYx tUT mo ve rIH Zyz JO',
    'cU Keq',
    'Sky duK FEL kO',
    'XwIH bez',
    'Ok C',
    'LV',
    'vRid Wy zIl kYg jA RAj Fum',
    'IJ gak',
    'zqOW Ju',
    'qa WyF RIf xo',
    'ot COq CUJ GO SY Fuv RUr vO',
    'PTE',
    'GaN lUP sI jeQ vYX Buk VYm',
    'bQIv kyh QIm Zyp Fys Pu dI',
    'a Byn GoQ',
    'Vy DEC VOh XUX caK zIt n',
    'PrAd WAp LEQ BYs fEH jAW',
    'A KY',
    'Ub ByP koC siq c',
    'zY GEF dos wI LoT bIV tOp',
    'dVoZ',
    'mDu Xu Cud vAX',
    'xqUx nuT wE ro vo niJ Ga PI',
    'ef hOd xYX ReF Geq Kaj loh t',
    'sKeP cUd ciS',
    'Dran zIx ren BeW hEP',
    'y QUz HUf fAX joH qOMe',
    'MGIk riQ gEX cOH SyK Hud d',
    'zOF du pEG',
    'din ti ded',
    'uf hYJ RIWdE',
    'BpeL faH BeF byq joZ jaF L',
    'iR wE ZIx KeZ pUW mOg HU',
    'Kan hiB CoZ ji',
    'tPOG JE ZyR TYc quL',
    'mLoJ PaX xyV gOh Nyxe',
    'jGYr jot rEH dAG HeK BU reZ',
    'Ej T',
    'hyS Me Rob rY CAp xat',
    'fEk dY',
    'wKA',
    'WxA LYrBe',
    'IF xEj No vad g',
    'Jri GeS TE sAW B',
    'TI',
    'JuJ tuR',
    'MYj FeG Wax SiR tYK',
    'qcyk DUN Ku CO',
    'oh teG TUk',
    'hTEH dY Lor Ryp dAn hED Dej',
    'ZneH syB di',
    'KkiJ pEm Lox',
    'NuQ gYK c',
    'yv Zil',
    'TOm xO ma gin hi',
    'Up rUw ZyS ZY FO sEx Qi',
    'tNAv mo nAW faT rUC DoV J',
    'lWYG b',
    'AP HYr jY nIJ WoB h',
    'fR',
    'uG wAp MUS fiC nYk jyl NYk',
    'DGYF zEc gun xiq PEH jA',
    'PJOK Xed SUh Xah jOz Zy',
    'CTUV maQ RIj Ra fEG',
    'bGY QIDE',
    'QdO ru',
    'i fiK WaZ',
    'wEj LOz DUS moS nEG',
    'u Fa nIZ',
    'GfAB nE Bat KIG',
    'hpIn feV Hi Ror l',
    'vrEs Qyq lo',
    'Njel lyk gil QO BaQ v',
    'Ul taB hoF',
    'GE CID we wE hAZ MYz wuw z',
    'xjaT cy lyp GOT',
    'YB JeB PiL PAS RAj',
    'NLi CAq Zy go',
    'i ve DUS tEJ pAK PeW XOZ Paw',
    'yf woh pi dIc tUz W',
    'wDoD TOH v',
    'bUg CYB nO',
    'zCaS NIJ JIq Ri lY bUf M',
    'JTIN cOJ vA',
    'JAf do Zu vIF poq feT GyP G',
    'Up xoL',
    'ah ti ZA jOM Rif Rag rUw Qyx',
    'nIg joZ gy Siz Res TUk FAf',
    'fpaf PiX VAx rYB XA FU LIj',
    'jFyB ZUM N',
    'GSAH dEx Byw ZUQ Rot',
    'zjuJ liB nYt hap GUj',
    'ol KOl TYL Me NOf cyx',
    'y lOB Xix cIn fIX qO',
    'KwOS',
    'MEd Nem NuW rEl Dyj mEq m',
    'hyZ MIs lOp PI JU rY RYt h',
    'NeN sAx Ga',
    'oh Za lEG VaQ',
    'oz WY Byt',
    'rFIX xEW Der BuM BIv DiXJe',
    'Wc',
    'JNOb gaH tAK diC TA Su Jy',
    'Fyk nyH GOz',
    'KBO XIZ bys NA baN la',
    'NVOv hO sod VI jyl boz HUH',
    'zmA co nE ca',
    'jeq gIQ',
    'jXuk KYz',
    'uT ce QOS PAc',
    'nliv Hy',
    'KQiT So',
    'vYQe',
    'Wk',
    'HluV WiS Su LEP cA SID m',
    'zA jaS vUW qU jyf xEG rU',
    'kNUg',
    'U FU ju jUn lEW JEr geg tUS b',
    'LQAX coN ho',
    'y bIT vIP Tow j',
    'il',
    'yP KyQ feh',
    'Yw B',
    'nnoC RYk cEb gyt C',
    'Jot kOV jU Po',
    'lDyL CyB',
    'SmaL sAp X',
    'cFyP',
    'CcIV jIp za Zin kO Hym QO zi',
    'PTuM Wig das Si Vim ZIZ S',
    'JAP zA qoS Py huk Tuxge',
    'zIR Geh ZOL PUd zuJ DI',
    'U DEG c',
    'IR DIL Fan BI Ba maG lOB',
    'cEb do mOc Xi goV',
    'NnYt QIg NO VI lYH pew BI',
    'nqar VeC Va pOF fI JiX n',
    'Ox ki Bo hiC s',
    'Pdy ju',
    'tY gip vyh Sy Xik Ga kOZ',
    'ffa VoDE',
    'riN',
    'jFUt tYf hEq VYs',
    'mOp DAf Wi pOb foR QAs',
    'cgUm Caj SU rEn F',
    'SZop wUt maR BEg Puh',
    'taW GaQ Hem su DU',
    'xIM Hah Va zI zEX',
    'PeL reH lUb cIK za wyR',
    'ZjaB RyZ Dof kUP JyH gI',
    'fYN MU',
    'ZHUp tIC jEH KAS MoL Mi',
    'lHYn ka zeq ciL tuf f',
    'SpyG fa zEH',
    'NRIb Siz Xaq SeF',
    'qfiZ QiG Te zU',
    'Pcon Con J',
    'eJ Cyz ceX',
    'UJ bOj diW',
    'DcyF RYt SIF mYj tYd GE MEj',
    'yl VAM qen mUJ K',
    'kZYG sEh lE tEr',
    'Pu xOx x',
    'oH be BEn BeR SA jI zAr',
    'y tEc',
    'Tze',
    'zHE',
    'fVOT Vup x',
    'XDuZ',
    'XPEC',
    'SWUXE',
    'Jl',
    'Rsem CIb hOk DUXZE',
    'sOD By HyQ wYn x',
    'XkuN REb CYr tAX F',
    'Ckut dUM hi TIT CA',
    'kOM saL raF HIl vIC',
    'xXit',
    'CBUg ne ziz Xog Sec CIK',
    'aB RUZ KES K',
    'vXyx',
    'cE DeC Get HU',
    'gij ZyD REz cu qU',
    'TxUg nif Ga LUN DUV Q',
    'NSux vAd qaC cE dIn Qa SUs X',
    'iC hA HAX cIg ris cy Le Gys',
    'GdOz',
    'pDos wAN muR tAZ mus G',
    'cvIZ XIh TO',
    'Iz MUJ w',
    'ED Puv ZAq FA QAF F',
    'TlUg JYv R',
    'Fan JAd TYp MAg Nol RuV W',
    'Uz QaK K',
    'yf saW zAB hur l',
    'GguB Hez s',
    'Ul JYB xYr Tuw waS Hir HOT',
    'STOr vI fin HIR nAk',
    'hmu',
    'AS Vu Za HEL KI sEx Pec RY',
    'NhA ju WY',
    'yZ WIh DIF hYs lEk',
    'SSEW FyM giG xyC LaT loL',
    'pt',
    'pJEz mUd fUT CUz J',
    'SfIJ qiB pER NuT ji',
    'GqO WYg lyc jyt mev pId',
    'kguZ S',
    'MzYk Pu cOD Ry Cev Ro',
    'JhA cU ciW dI',
    'WqAM noF gIM',
    'gJE SiS vET Jor giJ WADE',
    'Uq',
    'Ccan Cec',
    'Gax po',
    'GOb Niq XAn wOG nUk',
    'FqUB N',
    'Hpol Jix GeS zON v',
    'lJUl QUn gaj KEv rUg FY',
    'Tyq nEP ZaX Weh biN VEN HO',
    'nvyV zUG xej LYQ WOm maM H',
    'xzuQ NUz dES dA',
    'Rgoz hO POJ VIf VI',
    'aq Ko bIJ fA JEm WOq Qej h',
    'dguF jar P',
    'oL XeK mi rYJ',
    'yN QY fy xiB zE WuP PEm feg b',
    'ljoD kYx Duj HiQ',
    'iQ LIM FE ve HoP p',
    'XYq Xe ni vOD pAs zoH Soj',
    'XZIp sy rO Pu gy FA',
    'aQ WUS',
    'fvar',
    'KeR B',
    'kRuz j',
    'Ow SIQ bY',
    'rqIS kUQ LIz Pol DOHME',
    'tIX siH va',
    'KwOR HEv dab BIB K',
    'XPA dev wOf CEh dAw N',
    'BZIW cEP xOM Bum ZO CiX fu',
    'yR veC',
    'cHuh hIJ qiv KEb QAB j',
    'ZCAL REF QOT Ja',
    'QwUs Myk hYW Quj RI',
    'wiX ZyP rAc Go Pug Wo',
    'uK fUr ZiL HA HOV GY',
    'oS Ber XeP WuB Let Xaf TA',
    'ShyL',
    'uk Des sIz',
    'UT VEs Foz Cud NUL Ked Syq',
    'y LI kO jiW xuf BEj',
    'UG WYC Gom',
    'mYz lO RYd Ja Mad Mi hoM g',
    'Y MuM huN cyk',
    'tuq HOG XYd',
    'kQEH xoX RyP QYc LiC',
    'Sm',
    'Qs',
    'eJ fE loW wid FO tog',
    'hriJ jyW',
    'PYC',
    'cLUc cY',
    'qsIb mEj pIp GOR',
    'dPaP vuH su hi lod Ji',
    'xut wYx vEH ZeN',
    'O VaL CEt fE KuN NaF',
    'GlAv VuW JAz',
    'bmiR hEn feb RI te qa RaG',
    'wXYW wU MIh vUJ ZIC',
    'GaD teL cej mOK D',
    'nNOd gOz VOz VYz hoR',
    'TMyN mOc HUC ra mY',
    'Vcyl Q',
    'hwoM Gaq Mi',
    'MY SyB Kiw ZY xeh HYm ryL',
    'XmYC deg Nil',
    'GY KE ZYK qEm hAq zaJ lyG j',
    'A FIN pin Zuf xYL cu',
    'RmiT MEM Pab KU xEj M',
    'CXo',
    'RQeQ Z',
    'XZAg Puw xiC Taz TuG mAg vA',
    'AX Wux Kij Cyv qaS gIL Dit',
    'zaZ',
    'sa jAp sO nOv L',
    'Fpes tav soZ CEl SaQ WuQ nU',
    'PmIf qoL KE Cin vas miw',
    'RUs Ki wI VOk Ke fub M',
    'xVi beH BIr cO Ji rY hUh w',
    'Rhi',
    'MqIm R',
    'fGyV SIq dUn Ryg',
    'jMYX p',
    'qgAj hYz Fes',
    'vxom tEB Zen Wa',
    'tGUq gO Wu',
    'LbY feX fyw RAB bOR Pug',
    'GFeZ lUX',
    'ddiS',
    'a rE pID JyZ Ryv HUv',
    'o kO',
    'UP hA Naj ZYV juZ Dy',
    'SWOC S',
    'RziB fuS nE HeH Fu baf qYt',
    'CtYN',
    'yJ KaT',
    'xaK RA fuv TEp naV Qu',
    'Noj LYG JYV vy zY XaH z',
    'uN dEB',
    'i nyt Tyq QI xif n',
    'moV wof ri ky Ni vAZ myK',
    'Wo Xak ve TaG sIc wad r',
    'lne Nid LiB xeh gos geb',
    'Tyt LyG DyH',
    'Thof kuG rOd fOF G',
    'VAN qob Z',
    'gcaT Buk Nuz j',
    'ScUT',
    'ZDen',
    'zxac Lep SYw Baj',
    'Gu ZIs vOz zin',
    'VTys sI VOt Zy hI jA QuC',
    'Jqi xyN piR Q',
    'jEC N',
    'Yn Gus roF qAG Bol BOv',
    'Um zIk NI pEt qa JOD FAs',
    'LmUf KiP Few COK MOz',
    'NQYZ tod NYl',
    'QtIv x',
    'mhoM KoK cYl Hum s',
    'im HI bel k',
    'wYG ZUz ry vI',
    'LXik g',
    'CfYh jyX LOr zUs nUJ',
    'yM leQ ne RaX jAp tyL H',
    'Il ZOw cIM qef BIf Zub k',
    'rFaL QiJ xaw qA hy',
    'GXEm Zig SoT VUl KUh s',
    'RPiv cOH laH nu',
    'iW zat mesCE',
    'Ir FOp cE DOR b',
    'HhOH mA caT naw gUk SY',
    'wGO Hub gO',
    'sFIg qob TAv RYb Hut z',
    'eG sAw rA QI kUH riZ NYw NI',
    'HHIV gEl QA NUt Vyh GIQ bIr',
    'csyb CU laK mYL ve CUn',
    'CAV cUK BUC',
    'sBef Ke sA',
    'aK Qid x',
    'TpUh fe HIW bU VAq',
    'FRax Tav vof BO rAH VU',
    'hc',
    'bROB xu FY TUH SIr vyl WU NO',
    'bA poC sYK zi ja',
    'KMOw teq VOD quP gU',
    'Ci Jij MoP xYL cIJ',
    'IN Lon MY Gec Dir maS zUF H',
    'ik ry',
    'yL qEF Ruk k',
    'ppED TOz zA',
    'tTEZ rir Rep jiW DO',
    'sqOT FuGqE',
    'GYV faX maL nIn WOv VIV',
    'uk vop B',
    'NMUm Fuj FE dyk j',
    'gIG COr voL bYT s',
    'lSow FYg Ra',
    'fqu Wy koB HYm LUZ R',
    'Av moc K',
    'jzaw h',
    'wU TuF vEw da LEH W',
    'FBeH to',
    'mnih Mi KUj cO tap',
    'MreX pAN siQ sER ZYr l',
    'ga mYX LiC J',
    'CwIt lE CUN nA',
    'AN lIR GUC Hy GUnHe',
    'sQUl',
    'ZZaB fiw',
    'RbiR koq',
    'SmEL DEj Gy to',
    'ot',
    'kBoM Ry WOB mUQ',
    'BkeM HaP G',
    'CVEF Nab hin CiB D',
    'oJ NeH WYn qIq rAR pOM DIq',
    'nC',
    'hrYf Wer vo',
    'BhO Ny jOP HuT soP pyX N',
    'MTyh peD',
    'at Ju FIx WoQ JOt bom',
    'xWo',
    'QvaR vip VOB mES dUj TYP B',
    'hvYP',
    'Wbak xOR',
    'uM TeT BYR',
    'jA CU Kem HUs REb QIn SOl',
    'aR Bot fYz Feb MI',
    'QEN m',
    'JTYM',
    'eH paJ LeQ Hur wU HEF',
    'ky FO TE TUQ rIT DI',
    'EX m',
    'dXOl q',
    'RoF FId SOs Ja zO dEz',
    'dreg QEx vyx BYZ zA CEc MYW',
    'WI Lok guf MIh KUF ty',
    'I saW FOM ri DU MoZ vAr W',
    'rhe lUR',
    'fNyH qab NYd xod gIw',
    'xkAH ByF jAl GIX lyz',
    'rcyV gec mi',
    'yj ZYC wEK qYc',
    'siV FIR zur Ky',
    'Slyn',
    'DIZ CaQ xIs fun QYl SYx Z',
    'hTO kY ZOH mE PId fu PA',
    'PMu KAc Lik RIS BUr JUS b',
    'om cYB sOZ KeL KYh qEw',
    'AT kil zYZ Jic',
    'GHuM xy',
    'rPA voW LI BAM h',
    'wa geG W',
    'u pot COS lec C',
    'DCok moM ROC Ky jAn wiV r',
    'GpaR Na pYj',
    'PAk WOG fI byw hav POB BEg V',
    'WPoJ Ti fi jo Doz z',
    'VJEB py',
    'PtEm BY ra BAf haT Pi vUw',
    'GVEv hOn WAX Si xaG DE nYW',
    'eg',
    'O FYr Le za Hy Rik',
    'NO xiN x',
    'pbEm K',
    'KAK jOJ liL PYM JAt GU',
    'AJ bIt kep LOW juZ fYRme',
    'a pIH nA XAf gIQ Roj k',
    'MRU nY nI VYt VOC',
    'QruP xOd BuMbE',
    'lZ',
    'qUv',
    'aT qA',
    'FJO',
    'GfUh',
    'Df',
    'PE SEX vIH hAj VeM',
    'tFY wEv jEg ref zEW Hi hoS',
    'YC Vy qAs Rex jE XUr V',
    'XRYl dYS nO fAx wal Vo',
    'jNuw toP weJ HoF cuZ jyS ZA',
    'wC',
    'bDAh Suc vaB pAp Xar Z',
    'FUB vAW gU TIHRe',
    'KseM rEm cY',
    'Fly Jof dA CeK JA',
    'u ca sOF HAh DeS TOV',
    'fsUs',
    'lxaK hus zAQ XiL xEF',
    'spEd',
    'fRY',
    'RDal zYt rI mUh',
    'JNYf RY qu',
    'mfIB POf Cuk nIw gyh WOF',
    'pvY Zuc hEQ rUh',
    'MYl NIR dYw fyP',
    'mfEV LeC Qyg',
    'WOh mil hu',
    'un wel ju vaG',
    'AQ PeW JI LuT maW ta gu',
    'Ap wom',
    'US neX SIM qep Rag Wet B',
    'mnUD NuF sO wOQ sAS RiBVe',
    'nmU cYK myt lyf TEQ PUz',
    'GXiJ SEM',
    'Co Fe kyZ zi',
    'ag Zyd Jy PeR',
    'VTo',
    'o Jad huH kYc de LY XaT g',
    'riJ pA JaK Qam ZE tuC',
    'BU SUk WO PI Cah Luv D',
    'rCYw rec Wo wEN Pip fEgsE',
    'LZux Jo hUP',
    'ffIp pIC teK zAB peK WEd V',
    'RI rIh z',
    'tFeT wy zyR sO Pin mISQE',
    'LxI Cyv zuF vEl fys Fa',
    'ak gyF',
    'RFI pOf tYm Quh CAS tUw',
    'eR vEs zoM LuW hes v',
    'e gOg SYv C',
    'GY BEP SOk fEF Myp',
    'Yq siM xoM rej F',
    'JE mYH vAb VA',
    'TdYX Mid foj Jak pop d',
    'Tco sOV xy zA nAN GUm bup V',
    'PDUf kYH dEL HiR JaZ HUc Z',
    'Vnis nyj',
    'Ccif Zep PAM Het FOl w',
    'Rsix zY LE TYM',
    'jhIc VO',
    'fEx CO rIf Pu kIV',
    'DDA hIk Zyp vaf rI',
    'hXeT JAQ gUz hE Hof z',
    'gtow Fe TYw B',
    'PE',
    'nWe Zidhe',
    'PQ',
    'y JoV bUl HEb',
    'cGiR VEf mUj',
    'a JUL rEw REG vEM ri lIZzE',
    'e by tEJ rAB XiL',
    'Xuf li jUm G',
    'Od bUc buX PeM Zuh ZYZ Q',
    'GXe Tu',
    'Jtog pi nib R',
    'RBY nis Pi',
    'lDYQ VoD do VUh VE gO',
    'FnuT DaL VuN PE LUX',
    'XeW jOc qUm rUf sOf lit',
    'NWat xAV gaW miD KyF xi SI',
    'qmYN cen',
    'tbA Run WAd Hon SaR Cin s',
    'XO cod po',
    'en fi dAQ',
    'NJy',
    'rrAk sy Ju',
    'yW kO raQ fAc pAd laf fUV G',
    'GdAl cO FAt Zew MOF p',
    'WBAw QIW XI Cig m',
    'tas le ZEw so',
    'qGED JE Xo',
    'CqOn rYS pAc jYV fI bi Co lY',
    'Lyn ZaH ma QIn QuK jax w',
    'Dkov lE NUf SYv JA DuF bOv x',
    'Eg SOX mew boz GAT v',
    'wGip rog JeP fag V',
    'xoB cYT JYx vak',
    'ndIw Ho',
    'zli',
    'CsEG HUZ hU Cyn Vuz wik Now',
    'NaZ ZEH fu Jad GA zuC s',
    'XwoT DyJ',
    'zO ke BUW vIm Cuf Dum',
    'fKEn vUN PYV voH HY',
    'xxa nes QA',
    'txys fOK z',
    'TDUG gam biL fol RaB vA jYl',
    'tCEB zO',
    'lGym lOJ Ru',
    'Zdut qOV bY jyN naw',
    'mloB t',
    'lSAV JiZ vUZ NuQqE',
    'FwO bOG wY cAf',
    'wGYV Teh ZAJ Pes NaQ biZ M',
    'JBAd BIp fYj LEg lA mA',
    'pHaz RIJ',
    'ZJOs pa Fo la',
    'fwOP Zyn Wim',
    'uq REV JEB wyB bY',
    'FwOs Q',
    'fceg QYd ZO',
    'mwUd',
    'xmUX hEl W',
    'mHYb Xa rO',
    'sRuf buH wIw TuH dog f',
    'wSiD pUb BAS WOq',
    'NS',
    'KxIB moH HeG h',
    'HOC qe RiP fyw BY XOd tIw pO',
    'tvUc',
    'wNyb qA QOK d',
    'Nbyc cav Ne Dax FI',
    'fFe De di Qo',
    'uT Ji MIC si',
    'yJ ZEf ZE rA mUb XIt quS F',
    'SveQ ToZ DOV to TYp H',
    'yl tiP xAk wo',
    'mfir bAW kig suj lUz Web',
    'OB lYt wym WEx ros ned saNe',
    'iwxe',
    'nHiP ben byX nol TiX Pyc m',
    'Zbo MU Vis wU',
    'Jo hUZ BOB',
    'EC NoM kY zAx MuT',
    'Co',
    'nyD lAQ VO MOX hOT Vuv S',
    'vE',
    'e WEN Fyq rOR Hak Xa',
    'lgi koV vIt ryt xAK',
    'xWU',
    'cNEv WU wyb RYS tu bo',
    'GZEm kyw Tax k',
    'Uc HeQ nEs pac so',
    'I koS fEQ PU nyqGE',
    'I vo rOB cyd ha GyX ciB',
    'RZ',
    'VOm JEm KA',
    'syS qIc tUw fA',
    'gU VoM Ha Do',
    'Djig gIr COP NU dY byz',
    'rTYq Syz bOQ j',
    'Y fIv mUG nuf jOx h',
    'cGYc ti nIv sA',
    'mzO tU',
    'nzo',
    'BY DO KIK mI PuD vY NoH Daw',
    'BfEP qic XAv PUR HoM BAL',
    'O Lat F',
    'aT mAh pE Muw LUJ kEb P',
    'wQIx qyZre',
    'Jqy zum LOt Ga vOS V',
    'VaX jyH zAf Lo VuQ jEK LAs M',
    'e Luz QY jaG doM hIn ceH Ma',
    'ftak r',
    'AR Sah seJ cAm VOL f',
    'AM',
    'kDaw mO Weh XiR Kip JO',
    'Ur we QOP syR DiL RI',
    'mmOB vAg wIZ q',
    'YX GoD kA rI Jem fuw',
    'kXeH bYR HYr mI XIL BOz L',
    'VwAM wO giP kUQ HY Ved POs',
    'BiD jAp',
    'pzI loL DIb NAf X',
    'KoK g',
    'AS zUR Ji GiM nix cyQ F',
    'vPIc QA LUM xyd',
    'EV gUR PuT VUZ LyZ',
    'zNUh cIF TY',
    'EP ciR QEB PeQ RY BeD ger si',
    'hqU kUF maX nUd ZU Ma PU',
    'twI Ta Ny nO zeD ViS sy',
    'pXAW z',
    'jMe',
    'VpIW qoQ zI SO',
    'bFIT Qe wY pif Zi fyw',
    'bvUD mOk Gat gUr tiK Sud d',
    'Fcef CU Non hA dUX xI dY',
    'aN QyJ VY ni FYx Ly',
    'vOh JaR biH tuj Xaq xUD m',
    'hD',
    'GvI GEs mAc',
    'FED qeZ cov b',
    'vGEj Sy SE De QuC jUd B',
    'Rli WoF XE jyhfe',
    'iJ j',
    'XWa no Pyv',
    'NBev Bez POl gep Ze dyp n',
    'LFEn f',
    'vcOk tiq Xen',
    'xu Kyq wi cuv mi Gev KU raC',
    'wFAJ Ni PUt CUz gaJ vo',
    'hXaC pEd KAs',
    'ACre',
    'MMOl mYZ GA WUS BUR LiJ',
    'fcez biW gaK myC P',
    'bBiq',
    'prO',
    'sHYF wuV vEs Z',
    'SGet xU daW pY',
    'yF Qol PUf XUR fyb',
    'oM riG fyB sA',
    'ob Z',
    'BwUX HE XO',
    'tVUr gEh duT K',
    'eq xOJ kaF lAR SOq mYk Dyz',
    'lqAh',
    'dZy Ho SeW zoV FIL pAd REM q',
    'CjuL WI',
    'MqE',
    'oq r',
    'Fp',
    'PKY',
    'nFI',
    'NdoZ JO Gyx FyW LIz K',
    'PWic Qaw dUm v',
    'HgUd',
    'SfUH jYW',
    'zhU sad dUc wUg',
    'Ir Gop ceW mES FAC',
    'CS',
    'Jel tUV GEM dA Gy bAx',
    'oQ TY',
    'Mx',
    'RXe viT WIn tax',
    'oj qEf DI qex SEv g',
    'DGI wAH gAS gEh',
    'smo HUj nYr WyK LYl',
    'qrE fIZ dav Va Lid qaX',
    'ES sAP QYV DOw ha VUd dy',
    'ig NIH koM Ba coV h',
    'gHuZ WYm HeV bi mIT ti ZaP b',
    'LfiQ WU kAh TECe',
    'TnO Led MAF Z',
    'cJE jUR pU WeD LIq feR T',
    'khEk BIH SI wAv',
    'Uk Gi ZoJ lY cIM',
    'XWek ZyS gyZ syblE',
    'ZiG tIQ G',
    'Xqym ZUz',
    'lX',
    'fmoL DUC Zid su sElgE',
    'Am We Get Ja ra',
    'CHaM S',
    'dX',
    'OM vuH VuM wOJ dyF',
    'zZA Mo',
    'xIp hyx WUB Gik c',
    'wPos QuC XY',
    'NKIC Nap TeM Jov',
    'VEW keZ Wa HYq cYK dYM NUW',
    'JQat HOC',
    'gQeS n',
    'ID zem sO qYh PO nUq r',
    'SuZ BEK GY',
    'NrOZ sIg Da gOr QEz MaX',
    'vXAq h',
    'KOM Kog vIK piw HER tO QEL p',
    'msUQ',
    'Xmil jej PiH kEF rel gAL WI',
    'xLI',
    'PU',
    'TfY ra cAz soT pOP JYS kav q',
    'Iv Fib tuF TE xY vEJ JeK F',
    'qbi nuM viN JY QUME',
    'LFAd Tob Ca',
    'jtuh De juf KeKVe',
    'rRy Ri',
    'NyW RuC LYR Lad Pyw vuQ g',
    'kcOw paH j',
    'AJ HEf bar rEf Pi nO sOk',
    'u MO xY ka BOk QE PyL Xy Pi',
    'Fbek WU Pi CyhTE',
    'OC Myb vEW JIx',
    'zDuD SUV BUK pez Gyh VYd M',
    'kUd fAP HE Xe Qor BoT vux s',
    'LTYr Dod',
    'Aw wU',
    'QwOG FuD hIM Po Kyle',
    'tyr weC R',
    'CUf q',
    'XrAQ Fi pYZ bEP',
    'FgUr ZI NIt NOgje',
    'wcEh LId hav ki',
    'od QUw',
    'wfI SYj Cow ZY',
    'iH zIw MEV Ta rU',
    'eW ze BiZ lu TOr WEG PU',
    'Vwyt VoW doH xI wyp m',
    'E coQGE',
    'CHyk ko',
    'NkeS Wyg lI',
    'Bkam dUZ waX baZ FYN J',
    'WU',
    "po ke mon",
    "pan cake",
    "ho tel",
    "An na",
    "pyt hon",
    "dis cor d",
    "chal lenge",
    "de ve lop men t",
    "an d",
    "ran dom",
    "chat",
    "pas s",
    "sure",
    "am",
    "more",
    "than k",
    "ve ry",
    "re sul t",
    "we",
    "gon na",
    "pret ty",
    "star ted",
    "shor te nin g",
    "syl lab les",
    "there",
    "con se cu tive",
    "not hin g",
    "ac cor din g",
    "u ses",
    "use",
    "ad van ced",
    "dif fe ren t",
    "in to",
    "pro jec t",
    "wri tin g",
    "tes tin g",
    "so met hin g",
    "a ler tin g",
    "fa vo rite",
    "make",
    "syl lable",
    "snEXpe",
]